(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var T0=function(a){a.V("cardstatechange",a.Pg()&&a.Ti()?1:0)},U0=function(a,b){var c=g.La(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},GDa=function(a){var b=g.Eg(a);
a=g.Kg(a);return new g.cg(b.x,b.y,a.width,a.height)},HDa=function(a){return Math.pow(a,3)},IDa=function(a){return 3*a*a-2*a*a*a},X0=function(a){a=g.Oa(a);
delete V0[a];g.Mb(V0)&&W0&&W0.stop()},KDa=function(){W0||(W0=new g.L(function(){JDa()},20));
var a=W0;a.isActive()||a.start()},JDa=function(){var a=g.C();
g.Ab(V0,function(b){LDa(b,a)});
g.Mb(V0)||KDa()},Y0=function(a,b,c,d){g.un.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.i=a;this.J=b;this.duration=c;this.C=d;this.coords=[];this.progress=this.I=0;this.B=null},LDa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.I=1E3/(b-a.B);a.B=b;MDa(a,a.progress);1==a.progress?(a.Ma=0,X0(a),a.onFinish(),a.Ir()):a.Lb()&&a.tw()},MDa=function(a,b){"function"===typeof a.C&&(b=a.C(b));
a.coords=Array(a.i.length);for(var c=0;c<a.i.length;c++)a.coords[c]=(a.J[c]-a.i[c])*b+a.i[c]},NDa=function(a,b){g.Hl.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.I;this.state=b.Ma},Z0=function(a,b,c,d,e){Y0.call(this,b,c,d,e);
this.element=a},$0=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
Z0.call(this,a,b,c,d,e)},a1=function(a){g.J.call(this);
this.l=a||window;this.i=[]},b1=function(a){return a.baseUrl||null},c1=function(a,b){return g.He(g.Jc(a,b,void 0),function(c){return!!c})},ODa=function(a,b,c){function d(cb){var nb,yd,Ub,jc=cb.hovercardButton;
if(!jc)return null;jc=jc.subscribeButtonRenderer;if(!jc)return null;var af=f(jc.unsubscribedButtonText),bf=f(jc.subscribedButtonText);if(jc.subscribed){var nl=f(jc.subscriberCountWithUnsubscribeText);var mi=f(jc.subscriberCountText)}else nl=f(jc.subscriberCountText),mi=f(jc.subscriberCountWithSubscribeText);var Kf=null;return cb.signinEndpoint&&(Kf=U0(cb,"signinEndpoint","webNavigationEndpointData","url"),Kf||(Kf=null===(Ub=null===(yd=null===(nb=jc.signInEndpoint)||void 0===nb?void 0:nb.commandMetadata)||
void 0===yd?void 0:yd.webCommandMetadata)||void 0===Ub?void 0:Ub.url),!Kf)?null:af&&(bf||Kf)?{subscribed:jc.subscribed,subscribeText:af,subscribeCount:nl,unsubscribeText:bf,unsubscribeCount:mi,enabled:jc.enabled,signinUrl:Kf,classic:cb.useClassicSubscribeButton}:null}
function e(cb){if(cb){var nb=[],yd=cb.videoId;yd&&nb.push("v="+yd);(yd=cb.playlistId)&&nb.push("list="+yd);(cb=cb.startTimeSeconds)&&nb.push("t="+cb);return"/watch?"+nb.join("&")}}
function f(cb){if(!cb)return null;var nb=cb.simpleText;return nb?nb:cb.runs?g.Jc(cb.runs,function(yd){return yd.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=null,r=null,t=null,w=null,x=!1,y=null,F=null,E=null,G=null,I=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,r=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,t=f(b.playlistLength);else if("CHANNEL"===h){if(x=U0(l,"browseEndpoint","browseId"))w=x,m="/channel/"+w;n=!1;p="new";(x=!!b.isSubscribe)?y=d(b):F=f(b.subscribersText)}else"WEBSITE"===
h?((E=U0(l,"urlEndpoint","url"))&&(m=E),n=!0,p="new",E=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(G=f(b.productPrice)),b.additionalFeesText&&(I=f(b.additionalFeesText)),(n=U0(l,"urlEndpoint","url"))&&(m=n),n=!0,p="new");a=U0(b,"title","accessibility","accessibilityData","label");var H=b.endpoint?b.endpoint.clickTrackingParams:null,Aa="";if(b.metadata){var oa=f(b.metadata);oa&&(Aa=oa)}return{id:"element-"+c,type:h,title:f(b.title),metadata:Aa,callToAction:f(b.callToAction),
hD:b.image,iconUrl:E,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,playlistLength:t,channelId:w,subscribeButton:y,subscribersText:F,isSubscribe:x,targetUrl:m||null,ZL:n,Dd:H?{itct:H}:null,JQ:p,jq:a?a:null,cM:b.isPlaceholder,impressionUrls:c1(b.impressionUrls||[],b1),SL:c1(b.hovercardShowUrls||[],b1),clickUrls:c1(l.loggingUrls||[],b1),visualElement:g.eu(b.trackingParams),
productPrice:G,additionalFeesText:I}},d1=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:c1(a.impressionUrls||[],b1),elements:c1(a.elements||[],function(d,e){return ODa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.eu(a.trackingParams));return c},e1=function(a){g.iO.call(this,a);
this.u=this.endscreen=null;this.i={};this.C={};this.B=this.l=null;this.J=[];this.W=!0;this.I=0;a=a.T();this.L=g.UC(a)||g.XC(a);this.events=new g.aO(this);g.K(this,this.events);this.events.N(this.player,g.sG("creatorendscreen"),this.Ad);this.events.N(this.player,g.tG("creatorendscreen"),this.nf);this.events.N(this.player,"resize",this.Sa);this.events.N(window,"focus",this.IP);this.load();var b=g.Ce("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Zf(this,function(){g.Ge(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},PDa=function(a){return a.player.getVideoData().C?"current":a.L?"new":"current"},f1=function(a){return"creator-endscreen-editor"===a.player.T().playerStyle},QDa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.u&&a.u.abort();c={method:"POST",onFinish:function(e){var f=a.u=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=d1(f,PDa(a))));g1(a,f)},
urlParams:{v:c},withCredentials:!0};a.L&&(c.urlParams.ptype="embedded");var d=b.km;d&&(c.postParams={ad_tracking:d});if(b=g.pja(b))if(b=g.Ec(b),b=g.Ac(b))a.u=g.Yp(b,c)},g1=function(a,b,c){c=void 0===c?!0:c;
a.player.Qe("creatorendscreen");a.l&&(a.l.dispose(),a.l=null,a.B.dispose(),a.B=null);for(var d=g.q(Object.values(a.i)),e=d.next();!e.done;e=d.next())e.value.dispose();a.i={};a.C={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&RDa(a);c=[];d=new g.pG(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.T().i||(a.l=new g.W({D:"div",K:"ytp-ce-shadow"}),g.ZN(a.player,a.l.element,4),a.B=new g.GM(a.l,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=SDa(a,e);if(f){a.i[e.id]=f;a.C[e.id]=e;g.ZN(a.player,f.element,4);var h=new g.pG(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);TDa(a,f,e)}else g.jt(new g.Yr("buildEndscreenElement null",
e))}a.player.Kd(c);a.Sa()}},RDa=function(a){var b=g.iu(),c=g.ku();
c&&b&&a.endscreen.visualElement&&g.yu(c,b,a.endscreen.visualElement)},SDa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c=a.player.Z("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];c={D:"div",ka:["ytp-ce-element","ytp-ce-video"],U:{tabindex:"0","aria-label":b.jq||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-covering-image",U:h1(b)},{D:"div",K:"ytp-ce-covering-shadow-top"},{D:"a",K:"ytp-ce-covering-overlay",U:{href:i1(a,b.targetUrl),tabindex:"-1"},S:[{D:"div",ka:["ytp-ce-video-title"].concat(g.la(c)),U:{dir:g.An(b.title||
"")},ba:b.title},{D:"div",K:"ytp-ce-video-duration",ba:b.videoDuration||void 0}]}]};c=new g.W(c);break;case "PLAYLIST":c=a.player.Z("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];c={D:"div",ka:["ytp-ce-element","ytp-ce-playlist"],U:{tabindex:"0","aria-label":b.jq||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-covering-image",U:h1(b)},{D:"div",K:"ytp-ce-covering-shadow-top"},{D:"a",K:"ytp-ce-covering-overlay",U:{href:i1(a,
b.targetUrl),tabindex:"-1"},S:[{D:"div",ka:["ytp-ce-playlist-title"].concat(g.la(c)),U:{dir:g.An(b.title||"")},ba:b.title},{D:"div",K:"ytp-ce-playlist-count",S:[{D:"div",K:"ytp-ce-playlist-icon"},{D:"div",K:"ytp-ce-playlist-count-text",ba:b.playlistLength||void 0}]}]}]};c=new g.W(c);break;case "CHANNEL":c={D:"div",ka:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],U:{tabindex:"0","aria-label":b.jq||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},
{D:"div",K:"ytp-ce-expanding-overlay",S:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",S:[{D:"div",K:"ytp-ce-expanding-overlay-body",S:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",S:[{D:"a",ka:["ytp-ce-channel-title","ytp-ce-link"],U:{href:i1(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.An(b.title||"")},ba:b.title},b.subscribeButton?{D:"div",K:"ytp-ce-subscribe-container",S:[{D:"div",K:"ytp-ce-channel-subscribe"}]}:
"",b.subscribersText?{D:"div",K:"ytp-ce-channel-subscribers-text",ba:b.subscribersText}:"",b.metadata?{D:"div",ka:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],ba:b.metadata}:""]}]}]}]},{D:"div",K:"ytp-ce-expanding-image",U:h1(b)}]};c=new g.W(c);var d=g.oe(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.M(d,"ytp-ce-subscribe-button");if(a.player.T().i){var e=null;var f=b.Dd.itct}else e="endscreen",f=null;e=new g.jP(b.subscribeButton.subscribeText,
b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":c={D:"div",ka:["ytp-ce-element","ytp-ce-website"],U:{tabindex:"0","aria-label":b.jq||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-expanding-overlay",S:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},
{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",S:[{D:"div",K:"ytp-ce-expanding-overlay-body",S:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",S:[{D:"div",K:"ytp-ce-website-title",U:{dir:g.An(b.title||"")},ba:b.title},{D:"div",K:"ytp-ce-website-metadata",ba:b.metadata},{D:"a",ka:["ytp-ce-website-goto","ytp-ce-link"],U:{href:i1(a,b.targetUrl),target:"_blank",tabindex:"-1"},ba:b.callToAction}]}]}]}]},{D:"div",K:"ytp-ce-expanding-image",U:h1(b)},{D:"div",
K:"ytp-ce-expanding-icon",U:UDa(b.iconUrl)}]};c=new g.W(c);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={D:"div",K:"ytp-ce-merchandise-price-container",S:[{D:"div",K:"ytp-ce-merchandise-price",ba:b.productPrice}]},b.additionalFeesText&&c.S.push({D:"div",K:"ytp-ce-merchandise-additional-fees",ba:b.additionalFeesText})),c={D:"div",ka:["ytp-ce-element","ytp-ce-merchandise"],U:{tabindex:"0","aria-label":b.jq||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-expanding-overlay",
S:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",S:[{D:"div",K:"ytp-ce-expanding-overlay-body",S:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",S:[{D:"div",K:"ytp-ce-merchandise-title",U:{dir:g.An(b.title||"")},ba:b.title},c,{D:"div",K:"ytp-ce-merchandise-metadata",ba:b.metadata},{D:"a",ka:["ytp-ce-merchandise-goto","ytp-ce-link"],U:{href:i1(a,b.targetUrl),target:"_blank",tabindex:"-1"},ba:b.callToAction}]}]}]}]},
{D:"div",K:"ytp-ce-expanding-image",U:h1(b)},{D:"div",K:"ytp-ce-merchandise-invideo-cta-container",S:[{D:"div",K:"ytp-ce-merchandise-invideo-cta",ba:b.callToAction||void 0}]}]},c=new g.W(c)}b.cM&&g.M(c.element,"ytp-ce-placeholder");return c},h1=function(a){if(a.hD)var b=a.hD.thumbnails;
return UDa(b?b[b.length-1].url:null)},UDa=function(a){return a?{style:"background-image: url("+a+")"}:{}},TDa=function(a,b,c){function d(m){m&&(b.ya("blur",function(){"none"!=m.style.display&&a.W&&m.focus()}),b.N(m,"focus",f),b.N(m,"blur",h))}
function e(m){a.I+=m;0<a.I?(g.M(b.element,"ytp-ce-force-expand"),j1(a,c.id,!0)):(g.rn(b.element,"ytp-ce-force-expand"),g.rn(b.element,"ytp-ce-element-hover"),j1(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.ya("mouseenter",function(){k1(a,b,c)});
b.ya("mouseleave",function(){l1(a,b,c)});
a.player.T().i||b.ya("click",function(){g.M(b.element,"ytp-ce-element-hover")});
b.ya("click",function(m){VDa(a,c,m)});
b.ya("keypress",function(m){VDa(a,c,m)});
b.ya("focus",function(){k1(a,b,c)});
b.ya("blur",function(){l1(a,b,c)});
b.ya("touchstart",function(){k1(a,b,c)});
var l=g.qe("ytp-ce-expanding-overlay-hider",b.element);l&&b.N(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.rn(b.element,"ytp-ce-element-hover");g.rn(b.element,"ytp-ce-force-expand")});
b.ya("keydown",function(m){a.W=9===m.keyCode&&!m.shiftKey});
d(g.qe("ytp-sb-subscribe",b.element));d(g.qe("ytp-sb-unsubscribe",b.element));b.ya("focus",f);b.ya("blur",h)},VDa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.pn(d,"ytp-ce-element");){g.pn(d,"subscribe-label")&&m1(a,b);
if(g.pn(d,"ytp-ce-channel-subscribe"))return;d=g.Ie(d)}if(!d||g.pn(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.i[b.id])l1(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.JQ)m1(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Ec(i1(a,b.targetUrl)),c=g.Ac(c),g.FK(c,void 0,b.Dd);else{var e=a.player.getVideoData().C,f=function(){var h=i1(a,b.targetUrl),l=b.Dd,m=g.Gp(h);e&&m&&(m.v||m.list)?a.player.Ki(m.v,l,m.list,!1):g.EK(h,l)};
m1(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},i1=function(a,b){var c=a.player.T();
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.AD(c)+b}else return"";return b},k1=function(a,b,c){g.pn(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.M(b.element,"ytp-ce-element-hover"):a.player.T().i?(new g.L(function(){g.M(b.element,"ytp-ce-element-hover")},200)).start():g.M(b.element,"ytp-ce-element-hover"),n1(a,c.SL),j1(a,c.id,!0))},l1=function(a,b,c){g.rn(b.element,"ytp-ce-element-hover");
g.rn(b.element,"ytp-ce-force-expand");j1(a,c.id,!1)},j1=function(a,b,c){a.l&&(c?a.B.show():a.B.hide());
for(var d=g.q(Object.keys(a.i)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.N(a.i[e].element,"ytp-ce-element-shadow-show",c)},n1=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||f1(a))c&&c();else{b=WDa(a,b);var e=0,f=!1,h=new g.L(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.uq(b[a],d)}},m1=function(a,b,c){n1(a,b.clickUrls,c);
(a=g.ku())&&b.ZL&&g.Bu(a,b.visualElement)},WDa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(a.Hz(b[e],c));return d},XDa=function(a){return Array.isArray(a)&&a.length?a[0]:a},o1=function(a){return"string"===typeof a?a:""},p1=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},YDa=function(a){this.externalId=a},ZDa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.i=d},q1=function(a){return a.value?a.value:null},r1=function(a){if(!a)return null;
var b=g.Ec(o1(a.value));b=g.Ac(b);if(!b)return null;var c=p1(a.target,$Da,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new ZDa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},aEa=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},dEa=function(a){if(!a)return null;
var b=p1(a.type,bEa),c=p1(a.trigger,cEa),d=XDa(a.url);d=r1(d?d:null);a=XDa(a.subscribeData);var e=a?a:null;e?(a=o1(e.external_user_id),e=o1(e.subscription_token),a=a&&e?new YDa(a):null):a=null;return b?new aEa(b,c,d,a):null},eEa=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},gEa=function(a){return(a=fEa(a,function(b){return"openUrl"===b.type&&null!=b.url}))?a.url:null},fEa=function(a,b){return g.$a(a.action,b,void 0)},hEa=function(a,b){this.context=a;
this.i=b},t1=function(a){return a.customMessage?s1("div","iv-card-message",a.customMessage):""},u1=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{D:"div",K:"iv-card-image",U:{style:c},S:d}},v1=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.q(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(s1("li","",c.value));return{D:"ul",K:"iv-card-meta-info",S:b}},s1=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.An(c);return{D:a,U:b,ba:c}},iEa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.jt&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.jt+");");c.dir=g.An(a.customMessage);var d=[{D:"span",ba:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({D:"span",K:"iv-card-link-icon"}));return{D:"div",ka:b,U:c,S:d}},w1=function(a,b,c,d){if(d){b=g.q(b);
for(var e=b.next();!e.done;e=b.next())a.i(e.value,d,c.id,c.Dd,c.ng.click,5)}},jEa=function(a,b){this.merchant=a;
this.price=b},kEa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},lEa=function(a,b){return b?b:kEa(a)?"current":"new"},x1=function(a,b){g.J.call(this);
var c=this;this.element=a;this.context=b;this.Ka=!1;this.za=new Map;this.Da=new Map;this.context.G.addEventListener(g.sG("annotations_module"),function(d){(d=c.za.get(d))&&d.apply(c)});
this.context.G.addEventListener(g.tG("annotations_module"),function(d){(d=c.Da.get(d))&&d.apply(c)})},y1=function(a,b,c,d,e,f,h){a.context.i.ya(b,"click",function(l){a.uw(c,d,e,f||[],h||0,l)});
a.context.i.ya(b,"touchstart",function(){a.Ka=!1});
a.context.i.ya(b,"touchmove",function(){a.Ka=!0})},mEa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},z1=function(a,b,c){return{eE:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
hH:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
uv:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},C1=function(a,b,c){x1.call(this,b,c);
var d=this;this.G=a;this.eventId=null;this.la=this.Xa=this.u=this.ge=!1;this.ca=null;this.cards=[];this.Qa=this.L=this.ga=this.C=this.ma=this.i=null;this.X=[];this.J=this.Td=this.ia=null;this.I=0;this.ea=new g.L(g.Ia,c.B.sd?4E3:3E3);g.K(this,this.ea);this.Ha=new g.L(g.Ia);g.K(this,this.Ha);this.Y=new hEa(c,function(e,f,h,l,m,n){y1(d,e,f,h,l,m,n)});
this.W=new g.W({D:"div",K:"iv-drawer",U:{id:"iv-drawer"},S:[{D:"div",K:"iv-drawer-header",U:{"aria-role":"heading"},S:[{D:"span",K:"iv-drawer-header-text"},{D:"button",ka:["iv-drawer-close-button","ytp-button"],U:{"aria-label":"Hide cards",tabindex:"0"}}]},{D:"div",K:"iv-drawer-content"}]});g.K(this,this.W);this.B=this.W.element;this.Ia=new g.GM(this.W,330);g.K(this,this.Ia);this.Wa=g.qe("iv-drawer-header-text",this.B);this.l=g.qe("iv-drawer-content",this.B);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Xa&&A1(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Xa=d.u)&&B1(d)})},nEa=function(a,b){var c=b.data;
c.autoOpenMs&&a.addCueRange(c.autoOpenMs,0x8000000000000,"",function(){A1(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
c.autoCloseMs&&a.addCueRange(c.autoCloseMs,0x8000000000000,"",function(){B1(a)});
var d=c.headerText;g.Ke(a.Wa,d);a.L&&a.L.setAttribute("title",d);c.eventId&&(a.eventId=c.eventId);a.ia=g.eu(c.trackingParams);a.J=g.eu(c.closeTrackingParams);a.Td=g.eu(c.iconTrackingParams)},oEa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.I,type:"simple",teaserText:g.U(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Dd:D1(a,c,b,d),sponsored:!1,ng:z1(d,e,d.command),Xj:d.trackingParams?g.eu(d.trackingParams):null,Ph:e.trackingParams?g.eu(e.trackingParams):
null,Td:f&&f.trackingParams?g.eu(f.trackingParams):null,imageUrl:E1(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.U(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,jt:null,title:d.title?g.U(d.title):"",customMessage:d.callToAction?g.U(d.callToAction):"",url:d.command.urlEndpoint.url?r1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.command.urlEndpoint.url}):null};F1(a,c)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.I,type:"collaborator",teaserText:g.U(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Dd:D1(a,c,b,d),sponsored:!1,ng:z1(d,e,d.endpoint),Xj:d.trackingParams?g.eu(d.trackingParams):null,Ph:e.trackingParams?g.eu(e.trackingParams):null,Td:f&&f.trackingParams?g.eu(f.trackingParams):
null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.U(d.customText):null,pG:E1(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.U(d.channelName):"",metaInfo:[d.subscriberCountText?g.U(d.subscriberCountText):""],url:r1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};F1(a,c)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.I,type:"playlist",teaserText:g.U(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Dd:D1(a,c,b,d),sponsored:!1,ng:z1(d,e,d.action),Xj:d.trackingParams?g.eu(d.trackingParams):null,Ph:e.trackingParams?g.eu(e.trackingParams):null,Td:f&&f.trackingParams?g.eu(f.trackingParams):
null,zs:E1(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.U(d.customMessage):null,playlistVideoCount:g.U(d.playlistVideoCount),title:d.playlistTitle?g.U(d.playlistTitle):"",metaInfo:[d.channelName?g.U(d.channelName):"",d.videoCountText?g.U(d.videoCountText):""],url:r1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:mEa(d.action)})};F1(a,c)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.I,type:"video",teaserText:g.U(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Dd:D1(a,c,b,d),sponsored:!1,ng:z1(d,e,d.action),Xj:d.trackingParams?g.eu(d.trackingParams):null,Ph:e.trackingParams?g.eu(e.trackingParams):null,Td:f&&f.trackingParams?g.eu(f.trackingParams):null,zs:E1(d.videoThumbnail.thumbnails,258).url,
videoDuration:d.lengthString?g.U(d.lengthString):null,customMessage:d.customMessage?g.U(d.customMessage):null,title:d.videoTitle?g.U(d.videoTitle):"",metaInfo:[d.channelName?g.U(d.channelName):"",d.viewCountText?g.U(d.viewCountText):""],isLiveNow:!!d.badge,url:r1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:mEa(d.action)})};F1(a,c)}a.I++},E1=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},D1=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},qEa=function(a,b){var c=pEa(a,b);
c&&(c===a.i&&(a.i=null),a.G.removeCueRange(c.card.id),g.Ge(c.ix),g.ib(a.cards,c),a.lt(),G1(a))},A1=function(a,b,c){if(!a.u){a.Ia.show();
a.ma=new g.L(function(){g.M(a.context.G.getRootNode(),g.ET.IV_DRAWER_OPEN)},0);
a.ma.start();a.ca=g.ap(a.l,"mousewheel",function(h){a.ea.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.l.scrollTop+=h});
a.u=!0;var d=g.ku();d&&a.ia&&a.J&&g.zu(d,[a.ia,a.J]);b={TRIGGER_TYPE:b};for(var e=g.q(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.KE||(f.KE=!0,rEa(a.context.logger,f.card.ng.eE,b)),d&&g.zu(d,[f.card.Xj]);T0(a.G);c&&(a.C=new g.L(function(){a.ga=a.L;a.Qa.focus()},330),a.C.start())}},B1=function(a){a.u&&(a.Ia.hide(),g.bp(a.ca),a.ca=null,g.rn(a.context.G.getRootNode(),g.ET.IV_DRAWER_OPEN),a.u=!1,T0(a.G),a.C&&a.C.stop(),a.C=new g.L(function(){a.ga&&(a.ga.focus(),a.ga=null)},330),a.C.start())},tEa=
function(a){g.qn(a.element,[g.ET.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.ZN(a.G,a.B,5);sEa(a);a.L=g.qe("ytp-cards-button",a.G.getRootNode());a.Qa=g.qe("iv-drawer-close-button",a.B);a.ge=!0},sEa=function(a){var b=g.qe("iv-drawer-close-button",a.B);
a.context.i.ya(b,"click",a.JK,a);a.context.i.ya(a.l,"touchend",function(){a.ea.start()});
a.context.i.ya(a.l,"scroll",a.UK,a);a.context.l.subscribe("onHideControls",function(){a.la=!0});
a.context.l.subscribe("onShowControls",function(){a.la=!1});
a.context.l.subscribe("onVideoAreaChange",function(){a.la=g.pn(a.G.getRootNode(),"ytp-autohide")});
a.X.push(g.Go("iv-button-shown",a.gM,a));a.X.push(g.Go("iv-button-hidden",a.fM,a));a.X.push(g.Go("iv-teaser-shown",a.mJ,a));a.X.push(g.Go("iv-teaser-hidden",a.iM,a));a.X.push(g.Go("iv-teaser-clicked",a.lJ,a))},F1=function(a,b){a.ge||tEa(a);
qEa(a,b.id);var c=uEa(a,b);if(c){var d={card:b,ix:c.element,KE:!1},e=vEa(a,d);g.qb(a.cards,e,0,d);c.fa(a.l,e);a.lt();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.u||(a.i=d,G1(a),wEa(a,d),A1(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.G.getCurrentTime(),5E3>c&&c>b.startMs&&xEa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){xEa(a,d)}),G1(a))}},uEa=function(a,b){switch(b.type){case "simple":var c=a.Y;
var d=b.displayDomain?{D:"div",K:"iv-card-image-text",ba:b.displayDomain}:void 0;var e=iEa(b);d={D:"div",ka:["iv-card"],S:[{D:"a",K:"iv-click-target",U:{href:b.url?q1(b.url)||"":""},S:[u1(b.imageUrl,d),{D:"div",K:"iv-card-content",S:[s1("h2",void 0,b.title),e]}]}]};d=new g.W(d);w1(c,g.pe("iv-click-target",d.element),b,b.url);return d;case "collaborator":return c=a.Y,d={D:"div",ka:["iv-card","iv-card-channel"],S:[{D:"a",ka:["iv-click-target"],U:{href:q1(b.url)||"","data-ytid":b.channelId},S:[u1(b.pG),
{D:"div",K:"iv-card-content",S:[t1(b),{D:"h2",K:"iv-card-primary-link",ba:b.title},v1(b)]}]}]},d=new g.W(d),w1(c,g.pe("iv-click-target",d.element),b,b.url),d;case "playlist":return c=a.Y,d={D:"div",ka:["iv-card","iv-card-playlist"],S:[{D:"a",K:"iv-click-target",U:{href:q1(b.url)||""},S:[u1(b.zs,{D:"div",K:"iv-card-image-overlay",S:[{D:"span",K:"iv-card-playlist-video-count",ba:b.playlistVideoCount}]}),{D:"div",K:"iv-card-content",S:[t1(b),s1("h2","iv-card-primary-link",b.title),v1(b)]}]}]},d=new g.W(d),
w1(c,g.pe("iv-click-target",d.element),b,b.url),d;case "productListing":c=a.Y;var f=!g.eb(b.offers);d=["iv-card"];e="";var h=iEa(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",h=b.offers[0],f=[],h.price&&f.push({D:"div",K:"iv-card-offer-price",ba:h.price}),h.merchant&&f.push({D:"div",K:"iv-card-offer-merchant",ba:h.merchant}),h={D:"div",S:f});f=b.url?q1(b.url)||"":"";d={D:"div",ka:d,U:{tabindex:"0"},S:[{D:"a",ka:["iv-card-image","iv-click-target"],U:{style:"background-image: url("+
b.imageUrl+");",href:f,"aria-hidden":"true",tabindex:"-1"}},{D:"div",K:"iv-card-content",S:[b.sponsored?{D:"div",K:"iv-card-sponsored",S:["Sponsored",{D:"div",K:"iv-ad-info-container",S:[{D:"div",K:"iv-ad-info",ba:"{{adInfo}}"},{D:"div",K:"iv-ad-info-icon-container",S:[{D:"div",K:"iv-ad-info-icon"},{D:"div",K:"iv-ad-info-callout"}]}]}]}:"",{D:"a",K:"iv-click-target",U:{href:f},S:[s1("h2",e,b.title),h]}]}]};d=new g.W(d);e=g.Ce("span");g.Ke(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
d.Gc(e,"adInfo");w1(c,g.pe("iv-click-target",d.element),b,b.url);return d;case "video":return c=a.Y,e=b.videoDuration?{D:"span",K:"iv-card-video-duration",ba:b.videoDuration}:void 0,h=b.isLiveNow?{D:"span",ka:["yt-badge","yt-badge-live"],ba:"LIVE NOW"}:null,e={D:"div",ka:["iv-card","iv-card-video"],S:[{D:"a",K:"iv-click-target",U:{href:(null===(d=b.url)||void 0===d?void 0:q1(d))||""},S:[u1(b.zs,e),{D:"div",K:"iv-card-content",S:[t1(b),s1("h2","iv-card-primary-link",b.title),v1(b),h]}]}]},d=new g.W(e),
w1(c,g.pe("iv-click-target",d.element),b,b.url),d;default:return null}},vEa=function(a,b){if(0===a.cards.length)return 0;
var c=g.ab(a.cards,function(d){return b.card.startMs>d.card.startMs||b.card.startMs===d.card.startMs&&b.card.timestamp>=d.card.timestamp?!0:!1});
return-1===c?0:c+1},yEa=function(a){return a.i?"productListing"===a.i.card.type:g.th(a.cards,function(b){return"productListing"===b.card.type})},G1=function(a){g.N(a.G.getRootNode(),"ytp-cards-shopping-active",yEa(a))},xEa=function(a,b){if(!g.pn(a.G.getRootNode(),"ytp-cards-teaser-shown")){if(a.i!==b){var c=g.ku(),d=a.i?a.i.card.Td:a.Td;
c&&d&&g.Au(c,[d]);a.i=b;G1(a)}if(c="none"!=a.element.style.display)g.S(a.context.G.T().experiments,"html5_enable_single_video_vod_ivar_on_pacf")||2!==a.context.G.getPresentingPlayerType()?(c=a.context.G.getPlayerState(),d=0===c&&0===a.context.G.getCurrentTime(),c=1===c||3===c||d):c=1===a.context.G.getAdState();c&&b.card.teaserDurationMs&&a.G.Cp(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs});a.Ha.isActive()||((!a.u||!a.ea.isActive()&&a.la)&&wEa(a,b),a.Ha.start(910+b.card.teaserDurationMs))}},
wEa=function(a,b){if(a.W.ab){var c=new Y0([0,
a.l.scrollTop],[0,b.ix.offsetTop],600,IDa);a.context.u.ya(c,"animate",function(d){a.l.scrollTop=d.y});
a.context.u.ya(c,"finish",function(d){a.l.scrollTop=d.y});
c.play()}else g.TL(a.W,!0),a.l.scrollTop=b.ix.offsetTop,g.TL(a.W,!1)},H1=function(a){return a.i&&a.i.card?a.i.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},pEa=function(a,b){return g.$a(a.cards,function(c){return c.card.id===b})},I1=function(a,b,c){x1.call(this,a,b);
this.annotation=c;this.isActive=!1},zEa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},J1=function(a,b,c){I1.call(this,a,b,c);
this.l=null;this.J=!1;this.u=null;this.B=!1;this.i=this.I=this.C=null},AEa=function(a,b){var c=void 0===c?0:c;
var d=GDa(b).width;g.Cg(b,d);c=new $0(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,HDa);g.K(a,c);a.context.u.ya(c,"begin",function(){g.Lg(b,!0)});
c.play()},DEa=function(a,b){if(b.channel_name){var c=a.createElement({D:"div",
ka:["iv-branding-context-name"],ba:b.channel_name}),d=a.createElement({D:"div",ka:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.i=new g.jP(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signinUrl,a.context.G),a.i.fa(d));var f=a.createElement({D:"div",ka:["iv-branding-context-subscribe-caret"]}),h=a.createElement({D:"div",ka:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.Lg(h,!1);var l=a.createElement({D:"div",ka:["branding-context-container-outer"]});l.appendChild(h);g.ug(l,"right",b.image_width+"px");a.element.appendChild(l);a.u=new g.L(function(){BEa(a,h,l)},500);
g.K(a,a.u);a.context.i.ya(a.element,"mouseover",function(){CEa(a,h,l,f,b.image_height)});
a.context.i.ya(a.element,"mouseout",function(){a.u.start()})}},CEa=function(a,b,c,d,e){a.u.stop();
if(!a.B){var f=g.Kg(b);a.i||(b.style.width=g.Bg(f.width,!0),c.style.width=g.Bg(f.width,!0));g.ug(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.ug(d,"right","1px");a.B=!0;g.Lg(b,!0);a.C=new g.L(function(){g.M(this.element,"iv-branding-active")},0,a);
a.C.start()}},BEa=function(a,b,c){g.rn(a.element,"iv-branding-active");
a.I=new g.L(function(){g.Lg(b,!1);a.i||(c.style.width=g.Bg(0,!0))},250);
a.I.start();a.B=!1},EEa=function(a,b,c,d,e,f,h){this.i=a;
this.u=b;this.B=c;this.videoData=d;this.logger=e;this.G=f;this.l=h},K1=function(a,b,c){I1.call(this,a,b,c);
var d=this;this.L=this.isCollapsed=this.W=!1;this.I=5E3;this.l=this.u=this.i=this.B=null;this.J=this.createElement({D:"div",ka:["iv-promo-contents"]});this.C=new g.L(function(){d.i.setAttribute("aria-hidden","true");g.Lg(d.u,!1);g.Lg(d.l,!0)},700,this);
g.K(this,this.C)},FEa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promotion");a.element.tabIndex=0;var e=gEa(a.annotation),f=b.image_url;if(f){var h=a.createElement({D:"div",ka:["iv-promo-img","iv-click-target"]});f=a.createElement({D:"img",U:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({D:"span",K:"iv-promo-video-duration",ba:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({D:"span",K:"iv-promo-playlist-length",ba:b.playlist_length.toString()}),h.appendChild(f));e&&y1(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({D:"a",K:"iv-promo-txt"}),g.ed(f,q1(e)),a.i=f):a.i=a.createElement({D:"div",K:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({D:"p",S:[{D:"strong",
ba:b.text_line_1}]});var m=a.createElement({D:"p",S:[{D:"span",K:"iv-promo-link",ba:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({D:"button",ka:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({D:"button",ka:["iv-button","iv-promo-button"],S:[{D:"span",K:"iv-button-content",ba:f}]});var p=a.createElement({D:"div",K:"iv-promo-button-container"});p.appendChild(f);e&&y1(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.M(a.i,
"iv-click-target");e&&y1(a,a.i,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({D:"p",S:[{D:"span",ba:b.text_line_1}]}),m=a.createElement({D:"p",S:[{D:"strong",ba:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({D:"span",ka:["yt-badge","iv-promo-badge-live"],ba:"LIVE NOW"})),g.M(a.i,"iv-click-target"),e&&y1(a,a.i,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.i.appendChild(l);m&&a.i.appendChild(m);a.J.appendChild(a.i);p&&
a.J.appendChild(p);c=a.createElement({D:"div",K:"iv-promo-actions"});a.l=a.createElement({D:"button",ka:["iv-promo-expand","ytp-button"]});a.l.title="Expand";a.context.i.ya(a.l,"click",function(r){L1(a,5E3,r)});
c.appendChild(a.l);g.Lg(a.l,!1);a.context.i.ya(a.element,"mouseover",a.BL,a);a.context.i.ya(a.element,"mouseout",a.AL,a);a.context.i.ya(a.element,"touchend",function(r){L1(a,5E3,r)});
a.u=a.createElement({D:"button",ka:["iv-promo-close","ytp-button"]});a.u.title="Close";a.context.i.ya(a.u,"click","cta"===a.annotation.style&&b.text_line_3?a.vL:a.uL,a);c.appendChild(a.u);g.qn(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.J);a.element.appendChild(c)},L1=function(a,b,c){c.stopPropagation();
GEa(a);HEa(a,b);a.i.focus()},IEa=function(a){a.isCollapsed||a.L||a.B||(g.M(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.C.start())},GEa=function(a){a.C.stop();
a.isCollapsed&&(g.sn(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.i&&a.i.removeAttribute("aria-hidden"),g.Lg(a.l,!1),g.Lg(a.u,!0))},HEa=function(a,b){a.B||(a.B=g.Lm(function(){M1(this);
IEa(this)},b,a))},M1=function(a){a.B&&(g.A.clearTimeout(a.B),a.B=null)},JEa=function(a){this.G=a},rEa=function(a,b,c){b&&(c?N1(a,b.map(function(d){return g.en(d,c)})):N1(a,b))},N1=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.q(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.uq(m,f);d&&(e++,0!==d&&a.G.sendVideoStatsEngageEvent(d,f))},O1=function(a){g.iO.call(this,a);
var b=this;this.W=!1;this.loadNumber=0;this.J={};this.logger=new JEa(this.player);this.C=new g.aO(this);this.I=this.u=null;this.events=new g.aO(this);this.L=this.i=null;this.X=[];g.K(this,this.C);this.C.N(this.player,"onVideoAreaChange",function(){b.V("onVideoAreaChange")});
this.C.N(this.player,"onHideControls",function(){b.V("onHideControls")});
this.C.N(this.player,"onShowControls",function(){b.V("onShowControls")});
this.C.N(this.player,"resize",function(d){b.V("resize",d)});
this.C.N(this.player,"presentingplayerstatechange",function(d){b.V("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.nJ,this);this.subscribe("resize",this.Lu,this);this.player.T().L.subscribe("vast_info_card_add",this.bG,this);g.K(this,this.events);this.Y=this.createElement({D:"div",K:"video-custom-annotations"});this.l=new g.W({D:"div",ka:["ytp-player-content","ytp-iv-player-content"]});g.K(this,this.l);g.ZN(this.player,this.l.element,4);this.l.hide();this.B=new g.W({D:"div",ka:["ytp-iv-video-content"]});g.K(this,this.B);a=this.createElement({D:"div",K:"video-annotations"});
a.appendChild(this.Y);this.B.element.appendChild(a);this.Mn()&&this.load();var c=this.createElement({D:"style"});(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(c);g.Zf(this,function(){g.Ge(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},KEa=function(a){a=a.createElement({D:"div",
ka:["annotation","annotation-type-custom"]});g.Lg(a,!1);return a},LEa=function(a,b){var c=!b.isCued()&&!g.V(b,1024);
g.TL(a.l,c);g.TL(a.B,c)},MEa=function(a,b,c){a.W=!0;
a.I=g.Yp(b,c)},NEa=function(a,b){for(var c={},d=g.q(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Ma(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(NEa(a,e))}return c},QEa=function(a){var b=a.player.getVideoData();
if(b.ca){var c=a.player.T().L.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.Sp(h)&&h.responseXML?h.responseXML:null)&&P1(a,h)}};
g.rp()&&(d.onFinish=OEa(a,d.onFinish));d.postParams={ic_only:"1"};PEa(d,c);a.W=!0;g.Yp(b.ca,d)}}},PEa=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.wq&&(a.postParams.ic_coll=b.wq);b.qt&&(a.postParams.ic_xml=b.qt);b.Cs&&(a.postParams.ic_track=b.Cs)},REa=function(a){var b=new g.W({D:"div"});
g.Lg(b.element,!1);var c=new C1(a.player,b.element,Q1(a));g.K(c,b);b.fa(a.l.element);c.gs();return c},Q1=function(a){if(!a.L){var b=new a1(a);
g.K(a,b);var c=new g.G_(a);g.K(a,c);a.L=new EEa(b,c,a.player.T(),a.player.getVideoData(),a.logger,a.player,a.sd)}return a.L},P1=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.ku();if(e){var f=g.iu();f&&g.qu(g.Po("use_default_events_client")?void 0:g.bt,e,f,[g.eu(d)])}}d=b.getElementsByTagName("annotation");for(e=0;e<d.length;e++){var h=NEa(a,d[e]);f=null;try{if(h){var l=h.id,m=/.+/;var n="string"===typeof l&&null!=m&&null!=l&&l.match(m)?l:"";var p=p1(h.type,SEa),r=p1(h.style,TEa),t=o1(h.data),w=0!==t.length?JSON.parse(t):{};var x=h.action;h=dEa;if(null==x)var y=null;else if(g.La(x)){m=[];for(var F=g.q(x),E=F.next();!E.done;E=
F.next()){var G=h(E.value);G&&m.push(G)}y=m}else{var I=h(x);y=I?[I]:[]}f=n&&p?new eEa(n,p,r,y,w):null}else f=null}catch(yd){}if(f)if("branding"===f.type||"promotion"===f.type){h=a;m=f;var H=KEa(h),Aa=null;switch(m.type){case "branding":if(h.player.T().Jb)break;h.l.element.appendChild(H);Aa=new J1(H,Q1(h),m);break;case "promotion":g.ZN(h.player,H,4),Aa=new K1(H,Q1(h),m)}Aa&&Aa.gs();if(h=Aa)g.K(a,h),a.J[f.id]=h}else if("card"===f.type||"drawer"===f.type){a.i||(a.i=REa(a),g.K(a,a.i));if("card"===f.type){c=
a.i;var oa=f&&f.data&&f.data.card_type;h=f.data;if(oa)switch(m=h.tracking||{},m={eE:m.impression,click:m.click,close:m.close,hH:m.teaser_impression,uv:m.teaser_click},H=h.tracking_params||{},Aa=null,oa){case "collaborator":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Dd:h.session_data||{},sponsored:h.sponsored||!1,ng:m,Xj:H.card?g.eu(H.card):null,Ph:H.teaser?g.eu(H.teaser):null,Td:H.icon?
g.eu(H.icon):null,channelId:h.channel_id,customMessage:h.custom_message?h.custom_message:null,pG:h.image_url,title:h.title,metaInfo:h.meta_info,url:r1({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};F1(c,f);break;case "playlist":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Dd:h.session_data||{},sponsored:h.sponsored||!1,ng:m,Xj:H.card?g.eu(H.card):null,
Ph:H.teaser?g.eu(H.teaser):null,Td:H.icon?g.eu(H.icon):null,zs:h.image_url,playlistVideoCount:h.playlist_video_count,customMessage:h.custom_message?h.custom_message:null,title:h.title,metaInfo:h.meta_info,url:r1({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};F1(c,f);break;case "productListing":h.signin_url&&(Aa=r1({target:"current",value:h.signin_url}));oa=[];for(var cb=h.offers||[],nb=0;nb<cb.length;nb++)oa.push(new jEa(g.ld(cb[nb].merchant),g.ld(cb[nb].price)));
f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Dd:h.session_data||{},sponsored:h.sponsored||!1,ng:m,Xj:H.card?g.eu(H.card):null,Ph:H.teaser?g.eu(H.teaser):null,Td:H.icon?g.eu(H.icon):null,imageUrl:h.image_url,displayDomain:h.display_domain?h.display_domain:null,showLinkIcon:!!h.show_link_icon,jt:h.button_icon_url?h.button_icon_url:null,title:h.title,customMessage:h.custom_message?h.custom_message:
null,url:r1({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url}),d4:Aa,b4:h.signin_title?h.signin_title:void 0,a4:h.signin_message?h.signin_message:void 0,offers:oa};F1(c,f);break;case "simple":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Dd:h.session_data||{},sponsored:h.sponsored||!1,ng:m,Xj:H.card?g.eu(H.card):null,Ph:H.teaser?g.eu(H.teaser):null,Td:H.icon?
g.eu(H.icon):null,imageUrl:h.image_url,displayDomain:h.display_domain?h.display_domain:null,showLinkIcon:!!h.show_link_icon,jt:h.button_icon_url?h.button_icon_url:null,title:h.title,customMessage:h.custom_message?h.custom_message:null,url:r1({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};F1(c,f);break;case "video":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||
!1,Dd:h.session_data||{},sponsored:h.sponsored||!1,ng:m,Xj:H.card?g.eu(H.card):null,Ph:H.teaser?g.eu(H.teaser):null,Td:H.icon?g.eu(H.icon):null,zs:h.image_url,videoDuration:h.video_duration||null,customMessage:h.custom_message?h.custom_message:null,title:h.title,metaInfo:h.meta_info,isLiveNow:!!h.is_live_now,url:r1({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})},F1(c,f)}}else nEa(a.i,f);c=!0}}c&&(T0(a.player),a.Lu())},UEa=function(a,b){var c=!1;
a.i||(a.i=REa(a),g.K(a,a.i));for(var d=g.q(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(oEa(a.i,e.cardRenderer),c=!0);c&&(c=a.i,d=b.headerText?g.U(b.headerText):"",g.Ke(c.Wa,d),c.L&&c.L.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.ia=b.trackingParams?g.eu(b.trackingParams):null,c.J=b.closeButton.infoCardIconRenderer.trackingParams?g.eu(b.closeButton.infoCardIconRenderer.trackingParams):null,c.Td=b.icon.infoCardIconRenderer.trackingParams?
g.eu(b.icon.infoCardIconRenderer.trackingParams):null,T0(a.player),a.Lu())},VEa=function(a,b,c,d,e){if(!a.player.T().Jb){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new aEa("openUrl","click",new ZDa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;var m,n;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.U(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.U(b.subscriberCountText))):(b.subscriberCountText&&(e=g.U(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.U(b.subscriberCountWithSubscribeText)));var p=b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url?b.signInEndpoint.webNavigationEndpointData.url:(null===(n=null===(m=null===(l=b.signInEndpoint)||void 0===l?void 0:l.commandMetadata)||void 0===m?void 0:m.webCommandMetadata)||void 0===n?void 0:n.url)||"";l={subscribeText:g.U(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.U(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=
l}f=new eEa(c,"branding","branding",f,d);l=KEa(a);a.l.element.appendChild(l);f=new J1(l,Q1(a),f);f.gs();g.K(f,f);a.J[c]=f}},OEa=function(a,b){return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];
a.na()||(d.unshift(b),b=g.Pa.apply(window,d),a.X.push(g.pp(b)))}},WEa=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.SN.prototype.Cp=g.ca(15,function(a,b){var c=g.tO(this.Ua());c&&c.Cp(a,b)});
var V0={},W0=null;g.Ra(Y0,g.un);g.k=Y0.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.Ma)this.progress=0,this.coords=this.i;else if(this.Lb())return!1;X0(this);this.startTime=a=g.C();-1==this.Ma&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.B=this.startTime;this.progress||this.Ku();this.xh("play");-1==this.Ma&&this.xh("resume");this.Ma=1;var b=g.Oa(this);b in V0||(V0[b]=this);KDa();LDa(this,a);return!0};
g.k.stop=function(a){X0(this);this.Ma=0;a&&(this.progress=1);MDa(this,this.progress);this.xh("stop");this.Ir()};
g.k.pause=function(){this.Lb()&&(X0(this),this.Ma=-1,this.xh("pause"))};
g.k.da=function(){0==this.Ma||this.stop(!1);this.xh("destroy");Y0.Fd.da.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.tw=function(){this.xh("animate")};
g.k.xh=function(a){this.dispatchEvent(new NDa(a,this))};
g.Ra(NDa,g.Hl);g.Ra(Z0,Y0);Z0.prototype.u=g.Ia;Z0.prototype.tw=function(){this.u();Z0.Fd.tw.call(this)};
Z0.prototype.Ir=function(){this.u();Z0.Fd.Ir.call(this)};
Z0.prototype.Ku=function(){this.u();Z0.Fd.Ku.call(this)};
g.Ra($0,Z0);$0.prototype.u=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.u(a1,g.J);a1.prototype.ya=function(a,b,c,d){c=(0,g.B)(c,d||this.l);a=g.ap(a,b,c);this.i.push(a);return a};
a1.prototype.Vy=function(a,b,c,d){c=(0,g.B)(c,d||this.l);a=g.jp(a,b,c);this.i.push(a);return a};
a1.prototype.Gb=function(a){g.bp(a);g.ib(this.i,a)};
a1.prototype.da=function(){g.bp(this.i);this.i.length=0;g.J.prototype.da.call(this)};g.u(e1,g.iO);g.k=e1.prototype;g.k.load=function(){g.iO.prototype.load.call(this);if(!f1(this)){var a=g.qja(this.player.getVideoData());a?(a=d1(a,PDa(this)),g1(this,a,!1)):QDa(this)}};
g.k.unload=function(){g1(this,null);this.u&&(this.u.abort(),this.u=null);g.iO.prototype.unload.call(this)};
g.k.Ie=function(a,b){if(!f1(this))return null;if("loadCustomEndscreenRenderer"===a){var c=d1(b,"new");g1(this,c);return!0}return null};
g.k.getOptions=function(){return f1(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Sa=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<XEa.length;f++){var h=Math.abs(b.width-XEa[f]);if(-1===e||d>=h)e=f,d=h}d=YEa[e];this.l&&g.ug(this.l.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.i[f],
h=this.C[f],e&&h){var l=h.width*c/h.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.Jg(e.element,Math.round(h.width*a.width),f);g.Cg(e.element,m,n);g.sn(e.element,ZEa);m=h.left+h.width/2;h=h.top+l/2;g.M(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.sn(e.element,YEa);g.M(e.element,d);(e=g.oe(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.ug(e,"height",f+"px")}}}}};
g.k.Ad=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())n1(this,this.endscreen.impressionUrls),(a=g.ku())&&this.endscreen.visualElement&&g.ru(a,this.endscreen.visualElement,void 0);else{a=a.getId().substring(15);var b=this.i[a],c=this.C[a];g.M(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.M(b,"ytp-ce-shown");n1(this,c.impressionUrls);(b=g.ku())&&g.ru(b,c.visualElement,void 0);this.player.T().u&&this.player.xa("endscreenelementshown",
a)}};
g.k.nf=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.i[a];g.rn(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.rn(b,"ytp-ce-shown");this.player.T().u&&this.player.xa("endscreenelementhidden",a)}};
g.k.IP=function(a){var b=this;a.target===window&&(new g.L(function(){for(var c=g.q(Object.values(b.i)),d=c.next();!d.done;d=c.next())g.sn(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.k.Hz=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})};
var XEa=[346,426,470,506,570,640,853,1280,1920],YEa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),ZEa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var $Da={CU:"current",ZZ:"new"};var bEa={CLOSE:"close",l_:"openUrl",oK:"subscribe"},cEa={wS:"click",CLOSE:"close",VV:"hidden",B0:"rollOut",C0:"rollOver",j1:"shown"};var TEa={TR:"anchored",QH:"branding",CHANNEL:"channel",AU:"cta",YV:"highlightText",XW:"label",PLAYLIST:"playlist",Y_:"popup",u1:"speech",oK:"subscribe",L1:"title",VIDEO:"video",U2:"website"},SEa={QH:"branding",lS:"card",PU:"drawer",XV:"highlight",vY:"marker",j0:"promotion",TEXT:"text",b3:"widget"};g.u(x1,g.J);g.k=x1.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.pG(a,b,{id:c});a.namespace="annotations_module";d&&this.za.set(a,d);e&&this.Da.set(a,e);this.context.G.Kd([a])};
g.k.gs=function(){this.context.l.subscribe("resize",this.lt,this)};
g.k.uw=function(a,b,c,d,e,f){if(this.Ka)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Ge(this.element)};
g.k.lt=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=q1(a);if(f){var h=lEa(f,a.target),l=function(){a.i&&e.context.G.pauseVideo();var m=e.context.videoData.C||!1,n=g.Gp(f||"");m&&n&&(n.v||n.list)?e.context.G.Ki(n.v,b,n.list,!1):g.FK(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);N1(this.context.logger,c,l,d);kEa(f)||(c=g.ku(),d=b.itct,c&&d&&g.Bu(c,g.eu(d)))}};
g.k.da=function(){this.za.clear();this.Da.clear();g.J.prototype.da.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.K(this,a);return a.element};g.u(C1,x1);g.k=C1.prototype;g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.G.getRootNode())?(a=g.Kg(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.lt=function(){var a=this.isAvailable();g.Lg(this.element,a);g.N(this.context.G.getRootNode(),g.ET.IV_DRAWER_ENABLED,a);T0(this.G)};
g.k.destroy=function(){this.G.Cp(!1);try{this.G.getRootNode().removeChild(this.B)}catch(a){}g.Ho(this.X);g.bp(this.ca);this.ma&&this.ma.dispose();this.C&&this.C.dispose();x1.prototype.destroy.call(this)};
g.k.JK=function(){if(this.u){N1(this.context.logger,H1(this).ng.close);var a=g.ku();a&&this.J&&g.Bu(a,this.J);B1(this)}};
g.k.UK=function(){g.N(this.B,"iv-drawer-scrolled",0<this.l.scrollTop)};
g.k.gM=function(){var a=g.ku(),b=H1(this);b=b?b.Td:this.Td;a&&b&&g.zu(a,[b])};
g.k.fM=function(){var a=g.ku(),b=H1(this);b=b?b.Td:this.Td;a&&b&&g.Au(a,[b])};
g.k.mJ=function(){var a=H1(this);N1(this.context.logger,a.ng.hH);var b=g.ku();b&&a&&g.zu(b,[a.Ph,a.Td])};
g.k.iM=function(){var a=g.ku(),b=H1(this);a&&b&&g.Au(a,[b.Ph])};
g.k.lJ=function(a){var b=H1(this),c=g.ku();this.i?a?(a=this.context.logger,N1(a,b.ng.uv),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.Ph&&g.Bu(c,b.Ph)):(a=this.context.logger,N1(a,b.ng.uv),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.Td&&g.Bu(c,b.Td)):(a=this.context.logger,N1(a,b.ng.uv),a.G.sendVideoStatsEngageEvent(4,void 0),c&&this.Td&&g.Bu(c,this.Td))};g.u(I1,x1);I1.prototype.gs=function(){x1.prototype.gs.call(this);zEa(this)};
I1.prototype.show=function(){x1.prototype.show.call(this);var a=g.ku(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.zu(a,[g.eu(b.itct)])};
I1.prototype.hide=function(){x1.prototype.hide.call(this);var a=g.ku(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Au(a,[g.eu(b.itct)])};g.u(J1,I1);
J1.prototype.show=function(){if(!this.isActive){I1.prototype.show.call(this);if(!this.J){g.M(this.element,"iv-branding");var a=this.annotation.data;this.l=this.createElement({D:"img",ka:["branding-img","iv-click-target"],U:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Lg(this.l,!1);var b=this.createElement({D:"div",ka:["branding-img-container"]});b.appendChild(this.l);this.element.appendChild(b);(b=gEa(this.annotation))&&y1(this,this.l,b,this.annotation.id,
a.session_data);DEa(this,a);this.J=!0}g.Lg(this.element,!0);this.isActive=!0;this.l&&AEa(this,this.l)}};
J1.prototype.hide=function(){this.isActive&&(I1.prototype.hide.call(this),g.Lg(this.element,!1),this.isActive=!1)};
J1.prototype.destroy=function(){this.i&&(this.i.dispose(),this.i=null);I1.prototype.destroy.call(this)};g.u(K1,I1);g.k=K1.prototype;g.k.show=function(){this.isActive||(I1.prototype.show.call(this),this.W||(FEa(this),this.W=!0),g.Lg(this.element,!0),g.Lm(function(){g.rn(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,M1(this),GEa(this),HEa(this,this.I))};
g.k.hide=function(){this.isActive&&(g.M(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.uw=function(a,b,c,d,e,f){return this.isCollapsed?!1:I1.prototype.uw.call(this,a,b,c,d,e,f)};
g.k.BL=function(a){this.L=!0;L1(this,500,a)};
g.k.AL=function(){this.L=!1;IEa(this)};
g.k.uL=function(a){a.stopPropagation();this.hide()};
g.k.vL=function(a){a.stopPropagation();M1(this);this.isCollapsed=!0;g.M(this.element,"iv-promo-collapsed-no-delay");this.C.start()};
g.k.destroy=function(){this.C.dispose();I1.prototype.destroy.call(this)};g.u(O1,g.iO);g.k=O1.prototype;g.k.Ie=function(a,b){if(!WEa(this.player.T().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.F_(b);c&&P1(this,c);return!0;case "removeCustomAnnotationById":return b&&this.i&&(qEa(this.i,b),T0(this.player)),!0}return null};
g.k.getOptions=function(){return WEa(this.player.T().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Mn=function(){var a=this.player.T(),b=this.player.getVideoData();return b.C&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.zE||a.L.get(b.videoId)||g.eJ(b)||g.fJ(b)?!0:!1};
g.k.Lu=function(){if(this.B){var a=this.player.Ja().getVideoContentRect(!0);g.Jg(this.B.element,a.width,a.height);g.Cg(this.B.element,a.left,a.top)}if(this.i){var b=this.player.ij();a=this.i;b=b.width;g.N(a.B,"iv-drawer-small",426>=b);g.N(a.B,"iv-drawer-big",1280<=b)}};
g.k.nJ=function(a){LEa(this,a.state);g.V(a.state,2)&&(this.Pg()&&this.Ti()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Cp(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.I=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.Sp(h)&&h.responseXML?h.responseXML:null)&&(P1(b,h),g.M(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.iO.prototype.load.call(this);LEa(this,this.player.Va());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.rp()&&(a=OEa(this,a));var e={format:"XML",onFinish:a,onError:function(){b.I=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.T().L.get(d);f&&PEa(e,f);f=f&&(f.qt||f.wq);if(!c.Mk||f)c.ca?MEa(this,c.ca,e):(this.u=function(){b.Oa(e)},this.player.addEventListener("videodatachange",this.u));
g.ZN(this.player,this.B.element,4);this.Lu();(f=g.eJ(c))&&UEa(this,f);(f=g.fJ(c))&&f.featuredChannel&&VEa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.Oa=function(a){var b=this.player.getVideoData();b.ca&&(this.u&&(this.player.removeEventListener("videodatachange",this.u),this.u=null),MEa(this,b.ca,a))};
g.k.unload=function(){this.player.Qe("annotations_module");for(var a=g.q(Object.keys(this.J)),b=a.next();!b.done;b=a.next())this.J[b.value].destroy();this.L=null;this.i&&(this.i.destroy(),this.i=null,T0(this.player));this.W=!1;this.I&&(this.I.abort(),this.I=null);this.J={};this.l.hide();g.iO.prototype.unload.call(this);this.B.detach();this.u&&(this.player.removeEventListener("videodatachange",this.u),this.u=null)};
g.k.bG=function(a){a===this.player.getVideoData().videoId&&(this.loaded?QEa(this):this.load())};
g.k.Pg=function(){return!!this.i&&this.i.isAvailable()};
g.k.Ti=function(){this.Pg();return!!this.i&&this.i.u};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Pg();this.i&&(a?c?A1(this.i,c,b):A1(this.i,"YOUTUBE_DRAWER_AUTO_OPEN",b):B1(this.i))};
g.k.Cp=function(a,b){this.player.V(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.da=function(){this.player.T().L.unsubscribe("vast_info_card_add",this.bG,this);g.rn(this.player.getRootNode(),g.ET.IV_DRAWER_OPEN);for(var a=this.X,b=0,c=a.length;b<c;b++)g.sp(a[b]);this.X.length=0;g.iO.prototype.da.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.K(this,a);return a.element};g.oO.annotations_module=O1;g.oO.creatorendscreen=e1;})(_yt_player);
