(function(g){var window=this;var U1=function(a){a.isActive()||a.start()},V1=function(a){var b={languageCode:a.languageCode,
languageName:a.languageName,displayName:g.QH(a),kind:a.kind,name:a.name,id:a.id,is_servable:a.i,is_default:a.isDefault,is_translateable:a.isTranslateable,vss_id:a.vssId};a.translationLanguage&&(b.translationLanguage=a.translationLanguage);return b},W1=function(a){return a.translationLanguage?a.translationLanguage.languageCode:a.languageCode},$Ea=function(a,b){var c=new g.PH;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.i=a.i;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},aFa=function(){this.l=[];
this.i=[]},X1=function(a,b){return b?a.i.concat(a.l):a.i},Y1=function(a,b){switch(b.kind){case "asr":bFa(b,a.l);
break;default:bFa(b,a.i)}},bFa=function(a,b){g.$a(b,function(c){return c?a.toString()===c.toString():!1})||b.push(a)},Z1=function(){g.J.call(this);
this.l=new aFa;this.C=[]},$1=function(a,b,c){Z1.call(this,a);
this.audioTrack=c;this.i=null;this.C=b.LH},a2=function(){this.segments=[]},cFa=function(a,b){var c=g.tb(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.gb(a.segments,c),g.gb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.qb(a.segments,c,0,b),g.qb(a.segments,c+1,0,b)))},b2=function(a,b,c,d,e,f){g.J.call(this);
this.policy=a;this.player=b;this.X=c;this.I=d;this.C=e;this.L=f;this.W=this.player.T();this.B=new a2;this.l=this.u=this.i=null;this.J=new g.L(this.JE,1E3,this);this.events=new g.aO(this);g.K(this,this.J);g.K(this,this.events);this.events.N(b,"SEEK_COMPLETE",this.qB);this.qB();this.JE()},dFa=function(a,b){var c=g.Kx(g.Qx(b,a.policy,{})),d={format:"RAW",
withCredentials:!0};a.C&&(d.responseType="arraybuffer");a.l=g.xt(c,d,3,100).then(function(e){a:{a.na();if(a.u){var f=!(a.C?e.response:e.responseText)||400<=e.status,h=g.$A(e);if(h){e=g.Qx(a.u,a.policy,{});f=a.u;g.Fy(f.l,e,h);f.requestId=e.get("req_id");dFa(a,a.u);break a}f||null==a.I||(h=a.u.i[0],a.C?a.I(e.response,1E3*(h.startTime+a.player.tc())):a.I(e.responseText,1E3*(h.startTime+a.player.tc())))}a.u=null;a.l=null}});
a.u=b;cFa(a.B,a.u.i[0].va)},c2=function(a,b){Z1.call(this,b.T());
this.i=a;this.G=b;this.u=null;this.B=!1;this.I=g.rD(this.G.T())&&!this.i.isManifestless},eFa=function(a,b){var c=[],d;
for(d in a.i.i)if(a.i.i.hasOwnProperty(d)){var e=a.i.i[d];if(g.jO(e,b||null)){var f="en",h="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind;c.push(new g.PH({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},fFa=function(a,b){return null!=b&&b in a.i.i?a.i.i[b]:null},gFa=function(a,b,c){var d=[],e;
for(e in a.i.i)if(a.i.i.hasOwnProperty(e)){var f=a.i.i[e];if(g.jO(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},d2=function(a,b,c,d,e){Z1.call(this,e||null);
this.videoId=b;this.gE=d;this.B={};this.i=null;b=c||g.Gp(a).hl||"";b=b.split("_").join("-");this.u=g.Ip(a,{hl:b})},e2=function(a){if(!hFa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(iFa,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.substr(1),16);return[a>>16,a>>8&255,a&255]},f2=function(a,b,c,d,e,f){var h={};
g.Qa(h,b);g.Qa(h,a.params);g.Qa(h,c);var l={};g.Qa(l,b.Hc);a.params.Hc&&g.Qa(l,a.params.Hc);g.Qa(l,c.Hc);h.Hc=l;g.W.call(this,{D:"div",K:"caption-window",U:{id:"caption-window-"+a.id,dir:1===h.Ue?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:h.lang},S:[{D:"span",K:"captions-text",U:{style:"word-wrap: normal; display: block;"}}]});this.C=[];this.ca=!1;this.l=a;this.ia=this.ea=null;this.playerWidth=e;this.playerHeight=f;this.I=null;this.maxWidth=.96*e;this.za=.96*f;this.i=h;this.qb=c;this.B=
this.ha("captions-text");this.Wa=""!==this.B.style.getPropertyValue("box-decoration-break")||""!==this.B.style.getPropertyValue("-webkit-box-decoration-break");this.ga=d/360*16;this.type=0;this.Da=this.ga*jFa(l);a=new g.Vt(this.element,!0);g.K(this,a);a.subscribe("dragstart",this.qJ,this);a.subscribe("dragmove",this.pJ,this);a.subscribe("dragend",this.oJ,this);this.Ka=this.Ha=0;b="";this.i.windowOpacity&&(a=e2(this.i.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.i.windowOpacity+")");a={"background-color":b,
display:!1===this.i.isVisible?"none":"","text-align":kFa[this.i.textAlign]};this.Wa&&(a["border-radius"]=b?this.Da/8+"px":"");if(this.u=2===this.l.params.Ue||3===this.l.params.Ue)b=this.element,c="vertical-rl",1===this.i.oA&&(c="vertical-lr"),g.ve&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.ug(b,"-o-writing-mode",c),g.ug(b,"-webkit-writing-mode",c),g.ug(b,"writing-mode",c),g.ug(b,"text-orientation","upright"),g.M(b,"ytp-vertical-caption"),3===this.l.params.Ue&&(g.ug(b,"text-orientation",""),g.ug(b,"transform",
"rotate(180deg)"));g.ug(this.element,a);switch(this.i.ai){case 0:case 1:case 2:g.M(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.M(this.element,"ytp-caption-window-bottom")}},jFa=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},lFa=function(a,b){var c={},d=b.background?b.background:a.i.Hc.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.i.Hc.backgroundOpacity;d=e2(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Wa&&(c["box-decoration-break"]="clone",c["border-radius"]=a.Da/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.ga*jFa(b)+"px";d=1;e=b.color||a.i.Hc.color;if(b.color||null!=b.textOpacity)e=e2(e),d=null==b.textOpacity?a.i.Hc.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.lx&&(h=e=b.lx);var l=a.ga/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=r;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.gq()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.i.Hc.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.ki&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");
b.RL&&(c.visibility="hidden");1===b.bE&&a.u&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.wD||g.bs,3===a.l.params.Ue?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.Fi||2===b.Fi||3===b.Fi||4===b.Fi||5===b.Fi)if(g.wD)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Fi){case 4:case 3:c["text-emphasis-position"]="under left";
c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},mFa=function(a){a.I=g.Ce("SPAN");
g.ug(a.I,{display:"block"});g.M(a.I,"caption-visual-line");a.B.appendChild(a.I)},nFa=function(a,b){var c=g.Ce("SPAN");
g.ug(c,{display:"inline-block","white-space":"pre-wrap"});g.ug(c,lFa(a,b));c.classList.add("ytp-caption-segment");a.I.appendChild(c);c.previousElementSibling&&(g.ug(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.ug(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},oFa=function(a,b,c){a.ca=a.ca||!!c;
var d={};g.Qa(d,a.i.Hc);g.Qa(d,c||b.i);g.Qa(d,a.qb.Hc);(c=!a.I)&&mFa(a);for(var e=a.ea&&a.ia&&g.Pb(d,a.ia)?a.ea:nFa(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(mFa(a),e=nFa(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.De(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.wD||!g.yg(n.children[2],"text-emphasis")||(m=a.u?"padding-right":"padding-top",g.yg(n.children[2],"text-emphasis-position")&&(m=a.u?"padding-left":"padding-bottom"),
g.xe?g.ug(e,m,"1em"):g.ug(e,m,"0.5em")))}a.ia=d;a.ea=e;a.C.push(b)},g2=function(a,b,c,d,e,f,h){f2.call(this,a,b,c,d,e,f,h);
this.type=1},h2=function(a,b,c,d,e,f,h){f2.call(this,a,b,c,d,e,f,h);
this.type=2;this.J=[];this.X=this.L=this.la=0;this.Y=NaN;this.Qa=0;this.Xa=null;this.ma=new g.L(this.PO,433,this);g.M(this.element,"ytp-caption-window-rollup");g.K(this,this.ma);g.ug(this.element,"overflow","hidden")},pFa=function(a,b){if(!b)return"";
a.u&&1!==a.l.params.oA&&(b*=-1);return"translate"+(a.u?"X":"Y")+"("+b+"px)"},qFa=function(a){a.J=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.l.params.Ck,c=0,d=0,e=a.J.length-1;c<b&&-1<e;){var f=a.J[e];d+=a.u?f.offsetWidth:f.offsetHeight;c++;e--}a.J.length<b&&(d*=b/a.J.length);a.L=d;b=Math;c=b.max;isNaN(a.Y)&&((d=a.i.fl)?(e=g.Ce("SPAN"),g.Ke(e,"\u2013".repeat(d)),g.ug(e,lFa(a,a.i.Hc)),a.B.appendChild(e),a.Y=e.offsetWidth,a.B.removeChild(e)):a.Y=0);d=a.B;a.X=c.call(b,a.Y,a.Qa,(a.u?d.offsetHeight:d.offsetWidth)+1)},rFa=function(a,b){qFa(a);
var c=a.J.reduce(function(e,f){return(a.u?f.offsetWidth:f.offsetHeight)+e},0);
c=a.L-c;if(c!==a.la){var d=0<c&&0===a.la;b||isNaN(c)||d||(g.M(a.element,"ytp-rollup-mode"),g.kn(a.ma));g.ug(a.B,"transform",pFa(a,c));a.la=c}qFa(a)},i2=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.pG.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.i=h},j2=function(a,b,c,d,e){g.pG.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.i=[]},sFa=function(a){var b="_"+k2++;
return new j2(0,0x8000000000000,0,b,a)},uFa=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.Cd){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=tFa(l.textContent,n.textContent,p.textContent,f.textContent,h);return new i2(a,b,e,c,l,d,m)}switch(m.Cd){case 9:case 10:m.Fi=1;break;case 11:m.Fi=2;break;case 12:m.Fi=3;break;case 13:m.Fi=4;break;case 14:m.Fi=5}return new i2(a,b,e,c,l.textContent||"",d,m)},tFa=function(a,b,c,d,e){var f=g.gq(),h=
f?g.Ce("DIV"):g.Ce("RUBY"),l=g.Ce("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.Ce("DIV"):g.Ce("RP");a.textContent=b;h.appendChild(a);b=f?g.Ce("DIV"):g.Ce("RT");b.textContent=c;h.appendChild(b);c=e.Cd;if(10===c||11===c||12===c||13===c||14===c)if(g.ug(b,"text-emphasis-style","filled circle"),g.ug(b,"text-emphasis-color","currentcolor"),g.ug(b,"webkit-text-emphasis","filled circle"),11===e.Cd||13===e.Cd)g.ug(b,"webkit-text-emphasis-position","under left"),g.ug(b,"text-emphasis-position","under left");c=!0;if(4===e.Cd||7===e.Cd||12===e.Cd||
14===e.Cd)g.ug(h,"ruby-position","over"),g.ug(h,"-webkit-ruby-position","before");else if(5===e.Cd||6===e.Cd||11===e.Cd||13===e.Cd)g.ug(h,"ruby-position","under"),g.ug(h,"-webkit-ruby-position","after"),c=!1;e=f?g.Ce("DIV"):g.Ce("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.ug(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.ug(f,"display","none"),f=f.nextElementSibling,g.ug(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.ug(h.lastElementChild,"display","none"),d?(g.ug(h,"padding-top","0.6em"),g.ug(f,"top","0")):(g.ug(h,"padding-bottom","0.6em"),g.ug(f,"bottom","0")));return h},l2=function(){g.J.apply(this,arguments)},m2=function(a){l2.call(this);
this.C=a;this.B={};this.W={};this.X={};this.I="_"+k2++;this.L={};this.l=this.i=null;this.J=!0},n2=function(a,b){var c=a.getAttribute(b);
if(null!=c)return Number(c)},o2=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"===c},p2=function(a,b){var c=n2(a,b);
return void 0!==c?c:null},r2=function(a,b){var c=a.getAttribute(b);
if(null!=c)return q2.test(c),c},vFa=function(a,b){var c={},d=b.getAttribute("ws");
g.Qa(c,d?a.X[d]:a.C);d=p2(b,"mh");null!=d&&(c.ip=d);d=p2(b,"ju");null!=d&&(c.textAlign=d);d=p2(b,"pd");null!=d&&(c.Ue=d);d=p2(b,"sd");null!=d&&(c.oA=d);d=r2(b,"wfc");null!=d&&(c.windowColor=d);d=n2(b,"wfo");void 0!==d&&(c.windowOpacity=d/255);return c},wFa=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Qa(c,a.W[d]);d=p2(b,"ap");null!=d&&(c.ai=d);d=n2(b,"cc");null!=d&&(c.fl=d);d=n2(b,"ah");null!=d&&(c.bh=d);d=n2(b,"rc");null!=d&&(c.Ck=d);d=n2(b,"av");null!=d&&(c.Hi=d);return c},xFa=function(a,b,c,d){var e={};
g.Qa(e,wFa(a,b));g.Qa(e,vFa(a,b));d?g.Pb(e,a.C)?(d=a.I,e=a.C):d="_"+k2++:d=b.getAttribute("id")||"_"+k2++;a=n2(b,"t")+c;b=n2(b,"d")||0x8000000000000;if(2===e.Ue||3===e.Ue)c=e.Ck,e.Ck=e.fl,e.fl=c;return new j2(a,b,0,d,e)},s2=function(a){l2.call(this);
this.I=a;this.i=new Map;this.B=new Map;this.C=new Map;this.l=new Map},t2=function(a){a=g.Zd(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},yFa=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.B.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.C.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.Ck=a);b=b.ccColCount;void 0!==b&&(f.fl=b);if(2===f.Ue||3===f.Ue)b=f.Ck,f.Ck=f.fl,f.fl=b;return new j2(c,d,0,e,f)},v2=function(){this.u=this.time=this.mode=this.l=0;
this.B=new u2(this);this.C=new u2(this);this.i=[];this.clear()},AFa=function(a,b,c){if(255===a&&255===b||!a&&!b)return{Om:a,
Zk:b,result:0};a=zFa[a];b=zFa[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.Zk===d;if(d)return{Om:a,Zk:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Om:a,Zk:b,result:2};return{Om:a,Zk:b,result:3}},CFa=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.u&&a.reset(),a.B.l.clear(),a.C.l.clear()):(a.u=0,BFa(a.B,b,c,d))},DFa=function(a,b){a.i.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.q(a.i),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?CFa(a,d.HC,d.IC,b):1===d.type&&a.l&496&&BFa(a.C,d.HC,d.IC,b);a.i.length=0},w2=function(){this.type=0},x2=function(){this.state=this.Zk=this.Om=0},EFa=function(){this.timestamp=this.i=0},y2=function(a){this.C=a;
this.u=[];this.i=this.l=this.row=0;this.style=new w2;for(a=this.B=0;15>=a;a++){this.u[a]=[];for(var b=0;32>=b;b++)this.u[a][b]=new EFa}},z2=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.C.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var r=a.u[m][p];
if(0!==r.i){0===c&&(c=m,d=p);n=String.fromCharCode(r.i);var t=r.timestamp;t<e&&(e=t);r.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===r.i||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.B(c,d,e,l,f)}else for(d=c=0,f=e=a.C.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.u[h][m],r=p.i,0!==r&&(0===c&&(c=h,d=m),n=String.fromCharCode(r),t=p.timestamp,t<=e&&(e=t),l+=n,p.reset()),32===m||0===r)l&&b.B(c,d,e,f,l),e=f,l="",d=c=0},JFa=function(a,b){switch(a){case 0:return FFa[(b&127)-32];
case 1:return GFa[b&15];case 2:return HFa[b&31];case 3:return IFa[b&31]}return 0},A2=function(a){return a.u[a.row][a.l]},B2=function(a,b,c){2<=b&&1<a.l&&(--a.l,A2(a).i=0);
var d=A2(a);d.timestamp=a.C.time+0;d.i=JFa(b,c);32>a.l&&a.l++},KFa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.u[b+e][f],l=a.u[c+e][f];
h.i=l.i;h.timestamp=l.timestamp}},C2=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.u[b+d][e].reset()},D2=function(a){a.row=0<a.i?a.i:1;
a.l=1;C2(a,0,15)},E2=function(a){this.u=a;
this.C=0;this.style=new w2;this.I=new y2(this.u);this.J=new y2(this.u);this.text=new y2(this.u);this.l=this.I;this.B=this.J;this.i=this.l},F2=function(a,b,c){var d=a.l,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.i||(z2(d,c),D2(a.l),D2(a.B),d.row=15,d.i=b,e=!0)}a.style.set(3);a.i=d;a.i.style=a.style;a.u.mode=1<<d.B;e?d.l=1:d.i!==b&&(d.i>b?(z2(d,c),C2(d,d.row-d.i,b)):d.row<b&&(b=d.i),d.i=b)},LFa=function(a){a.style.set(1);
a.i=a.B;a.i.i=0;a.i.style=a.style;a.u.mode=1<<a.i.B},MFa=function(a){a.style.set(4);
a.i=a.text;a.i.style=a.style;a.u.mode=1<<a.i.B},u2=function(a){this.i=a;
this.C=0;this.u=new E2(this.i);this.I=new E2(this.i);this.l=new x2;this.B=this.u},BFa=function(a,b,c,d){a.l.update();
b=AFa(b,c,a.l);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Om;c=b.Zk;if(32<=e||!e)a.i.mode&a.i.l&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.B.i,b&96&&B2(a,0,b),c&96&&B2(a,0,c),0!==b&&0!==c&&3===a.style.type&&z2(a,d));else if(e&16)a:if(!a.l.matches(e,c)&&(b=a.l,b.Om=e,b.Zk=c,b.state=2,b=e&8?a.I:a.u,a.B=b,a.i.mode=1<<(a.C<<2)+(b.C<<1)+(4===b.style.type?1:0),(a.i.mode|1<<(a.C<<2)+(b.C<<1)+(4!==b.style.type?1:0))&a.i.l))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.i;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.i&&(d=c.i,d===c.row))break;var f=1+c.row-c.i,h=1+d-c.i;KFa(c,h,f,c.i);b=f;e=c.i;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));C2(c,b,e)}}c.row=d;c.l=a+1}else switch(e&7){case 1:switch(c&112){case 32:B2(b.i,0,32);break a;case 48:57===c?(d=b.i,A2(d).i=0,32>d.l&&d.l++):B2(b.i,1,c&15)}break;case 2:c&32&&B2(b.i,2,c&31);break;case 3:c&32&&B2(b.i,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:LFa(b);
break;case 33:d=b.i;1<d.l&&(--d.l,A2(d).i=0);break;case 36:d=b.i;b=A2(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.u[a][c]===b){for(;32>=c;c++)d.u[a][c].reset();break}break;case 37:F2(b,2,d);break;case 38:F2(b,3,d);break;case 39:F2(b,4,d);break;case 40:B2(b.i,0,32);break;case 41:b.style.set(2);b.i=b.l;b.i.i=0;b.i.style=b.style;b.u.mode=1<<b.i.B;break;case 42:d=b.text;d.i=15;d.style.set(4);D2(d);MFa(b);break;case 43:MFa(b);break;case 44:a=b.l;switch(b.style.get()){case 1:case 2:case 3:z2(a,d)}C2(a,
0,15);break;case 45:b:{a=b.i;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.l=1;break b}case 3:}2>a.i&&(a.i=2,a.row<a.i&&(a.row=a.i));b=a.row-a.i+1;z2(a,d);KFa(a,b,b+1,a.i-1);C2(a,a.row,1)}break;case 46:C2(b.B,0,15);break;case 47:z2(b.l,d),b.B.updateTime(b.u.time+0),d=b.B,b.B=b.l,b.l=d,LFa(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.i,32<(d.l+=c&3)&&(d.l=32)}}},NFa=function(){},G2=function(a,b,c){this.J=a;
this.I=c;this.version=this.C=this.u=this.byteOffset=0;this.i=new DataView(this.J);this.l=[]},H2=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.i.getUint8(b)},I2=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.i.getUint32(b)},J2=function(a,b){l2.call(this);
this.l=a;this.B=b;this.track="CC3"===this.B.languageName?4:0;this.i=new v2;this.i.l=1<<this.track},K2=function(a){if("string"===typeof a)return!1;
a=new G2(a,8,0);return OFa(a)},OFa=function(a){if(!(a.byteOffset<a.i.byteLength)||1380139777!==I2(a))return!1;
a.version=H2(a);if(1<a.version)return!1;H2(a);H2(a);H2(a);return!0},L2=function(){l2.call(this)},PFa=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.ki=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new i2(b,c,d,e.id,p.nodeValue,f||0<n,g.Mb(l)?void 0:l),m.push(p),e.i.push(p);else{var r={};g.Qa(r,l);PFa(a,b,c,d,e,!0,p,r,m)}}},M2=function(a){var b=a.split(":");
a=0;b=g.q(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},QFa=function(a,b,c,d){d=Object.assign({ip:0},d);
return new j2(a,b,c,"_"+k2++,d)},N2=function(a){g.J.call(this);
this.l=a;this.i=null},SFa=function(a){var b={};
if(a=W1(a))b.lang=a,RFa.test(a)&&(b.Ue=1);return b},Q2=function(a){g.iO.call(this,a);
var b=this;this.G=a;this.l=this.G.T();this.videoData=this.G.getVideoData();this.Qa=this.G.Ja();this.B={Hc:{}};this.C={Hc:{}};this.Y=[];this.W={};this.ma={};this.X=!1;this.Ha=g.mpa(this.videoData,this.G);this.Wa=!!this.videoData.captionTracks.length;this.Xa=!!this.videoData.oh;this.Ia="3"===this.l.controlsType;this.u=this.J=this.L=this.la=this.Da=null;this.za=new N2(this.l);this.i=null;this.ia=new g.aO(this);var c=null,d=g.go("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.Jn(d));this.storage=
c;c=a.nd();d=!(!c||!c.ws());this.Ka=!(!c||!c.xs());this.I=this.Ia&&d&&!this.Ha;this.ea=!this.I&&this.Ia&&this.Ka&&this.Ha;g.K(this,this.za);this.I?this.ga=this.ca=null:(this.ca=new g.gn(this.uH,void 0,this),g.K(this,this.ca),this.ga=new g.L(this.jQ,2E3,this),g.K(this,this.ga));g.K(this,this.ia);this.I||this.ia.N(a,"resize",this.GA);this.ia.N(a,"onPlaybackAudioChange",this.ZM);this.ia.N(a,g.sG("captions"),function(e){b.Ad(e)});
this.ia.N(a,g.tG("captions"),function(e){b.nf(e)});
O2(this,P2(this,"display-settings")||{})},TFa=function(a){if(1===a.l.ma||1===a.videoData.ho||"alwayson"===g.YI(a.videoData,"yt:cc"))return!0;
if(2===a.l.ma){var b;g.vD(a.l)?b=(0,g.XCa)():b=P2(a,"module-enabled");if(null!=b)return!!b}if(a.videoData.captionTracks.length)var c=a.player.getAudioTrack().u;b=a.player.getAudioTrack().captionsInitialState;var d=g.YI(a.videoData,"yt:cc");if(void 0===R2(a)){if("CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"===b)return d?"on"===d:!0;if("CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED"===b)return"on"===d}else return"on"===d;return"ON"===c||"on"===g.YI(a.videoData,"yt:cc")},S2=function(a,b){if(a.i&&(void 0===b||!b)||
!a.videoData.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.l||"FORCED_ON"===c.u},R2=function(a){var b=void 0,c=g.Xq(g.Vq.getInstance(),65);
if(g.vD(a.l)&&null!=c){if(null!=(0,g.XCa)())return!1;b=!c}return b},U2=function(a,b){if(a.u){if(a.J&&a.J.C)return a.J.C;
var c=b;c||(c=a.Xa?!1:a.Wa?!1:!0);c=X1(a.u.l,c);for(var d=[a.videoData.captionsLanguagePreference,a.l.captionsLanguagePreference,g.YI(a.videoData,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(W1(c[f])===d[e])return c[f];return a.J&&a.J.B?a.J.B:(d=c.find(function(h){return h.isDefault}))?d:c[0]||T2(a)}return null},T2=function(a){return a.J&&a.J.l},V2=function(a){var b=T2(a);
return!!b&&a.i===b},UFa=function(a,b){for(var c=a.G.nd().le().textTracks,d=a.i.toString(),e=0;e<c.length;e++){var f=c[e];
f.id===d&&(b?"showing"!==f.mode&&(f.mode="showing"):"showing"===f.mode&&(f.mode="disabled"))}},X2=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.X=c,a.X&&(g.vD(a.l)?(0,g.e0)(!!b):W2(a,"module-enabled",!!b)));a.i=b;S2(a)&&(a.i=T2(a));a.load()},VFa=function(a,b){var c=a.Qa.getVideoContentRect(!0).height;
if(!c)return null;var d=a.i?a.i.languageCode:null;!b.params.Ue&&d&&RFa.test(d)&&(b.params.Ue=1);d=a.Qa.getPlayerSize();switch(null!=b.params.ip?b.params.ip:1<b.i.length?1:0){case 1:return new g2(b,a.B,a.C,c,d.width,d.height,a.l.experiments);case 2:return new h2(b,a.B,a.C,c,d.width,d.height,a.l.experiments);default:return new f2(b,a.B,a.C,c,d.width,d.height,a.l.experiments)}},O2=function(a,b,c){c=void 0===c?!1:c;
var d=Y2.Hc;a.B={};g.Qa(a.B,Y2);a.B.Hc={};g.Qa(a.B.Hc,d);a.C={Hc:{}};var e=b.backgroundOverride?a.C:a.B,f=b.background||d.background;q2.test(f);e.Hc.background=f;e=b.colorOverride?a.C:a.B;f=b.color||d.color;q2.test(f);e.Hc.color=f;e=b.windowColorOverride?a.C:a.B;f=b.windowColor||Y2.windowColor;q2.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.C:a.B;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Hc.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.C:a.B;f=b.fontSizeIncrement;null==
f&&(f=d.fontSizeIncrement);e.Hc.fontSizeIncrement=f;f=b.fontStyleOverride?a.C:a.B;e=b.fontStyle;null==e&&(e=d.bold&&d.ki?3:d.bold?1:d.ki?2:0);f=f.Hc;switch(e){case 1:f.bold=!0;delete f.ki;break;case 2:delete f.bold;f.ki=!0;break;case 3:f.bold=!0;f.ki=!0;break;default:delete f.bold,delete f.ki}e=b.textOpacityOverride?a.C:a.B;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Hc.textOpacity=f;e=b.windowOpacityOverride?a.C:a.B;f=b.windowOpacity;null==f&&(f=Y2.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?
a.C:a.B;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Hc.charEdgeStyle=f;e=b.fontFamilyOverride?a.C:a.B;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Hc.fontFamily=f;a.loaded&&a.GA();c&&W2(a,"display-settings",b)},XFa=function(a,b){if(b&&!a.L){var c=sFa({Ue:0,
lang:"en-GB"});a.L=[c,new i2(c.start,c.end-c.start,0,c.id,"Captions look like this")];a.player.Kd(a.L)}else!b&&a.L&&(WFa(a,a.L),a.L=null)},WFa=function(a,b){a.player.jg(b);
g.yb(b,function(c){g.ib(this.Y,c)},a);
U1(a.ca)},P2=function(a,b){if(!a.storage)return null;
try{var c=a.storage.get(b)}catch(d){a.storage.remove(b)}return c},W2=function(a,b,c){if(a.storage)try{a.storage.set(b,c)}catch(d){}};
g.wO.prototype.yq=g.ca(23,function(){this.aa();for(var a=g.oe(document,"track",void 0,this.i),b=0;b<a.length;b++)g.Ge(a[b])});
g.QS.prototype.yq=g.ca(22,function(){this.i.yq()});
g.wO.prototype.xs=g.ca(21,function(){return!(!this.i.textTracks||!this.i.textTracks.addEventListener)});
g.QS.prototype.xs=g.ca(20,function(){return this.i.xs()});
g.wO.prototype.ws=g.ca(19,function(){return!!this.i.textTracks});
g.QS.prototype.ws=g.ca(18,function(){return this.i.ws()});
g.wO.prototype.mq=g.ca(17,function(a){this.aa();for(var b=0;b<a.length;b++)this.i.appendChild(a[b])});
g.QS.prototype.mq=g.ca(16,function(a){this.i.mq(a)});
g.Iy.prototype.Wt=g.ca(1,function(){return 0});
g.mz.prototype.Wt=g.ca(0,function(a){return(a=this.ci(a))?a.l:0});
var RFa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i;g.u(Z1,g.J);g.k=Z1.prototype;g.k.pu=function(){};
g.k.qu=function(){};
g.k.Ik=function(){};
g.k.No=function(){return""};
g.k.oG=function(){return!1};
g.k.da=function(){this.Ik();g.J.prototype.da.call(this)};
g.u($1,Z1);$1.prototype.pu=function(a,b,c){var d=this;this.na();b=this.No(a,b);this.Ik();this.i=g.Yp(b,{format:"RAW",onSuccess:function(e){d.i=null;c(e.responseText,a)},
withCredentials:!0})};
$1.prototype.qu=function(a){if(this.audioTrack)for(var b=g.q(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())Y1(this.l,c.value);a()};
$1.prototype.No=function(a,b){var c=a.url,d={fmt:b};if("srv3"===b||"3"===b||"json3"===b)g.gq()?Object.assign(d,{xorb:2,xobt:1,xovt:1}):Object.assign(d,{xorb:2,xobt:3,xovt:3});a.translationLanguage&&(d.tlang=W1(a));return g.Ip(c,d)};
$1.prototype.Ik=function(){this.i&&this.i.abort()};
a2.prototype.contains=function(a){a=g.tb(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
a2.prototype.length=function(){return this.segments.length/2};
g.u(b2,g.J);g.k=b2.prototype;g.k.da=function(){g.J.prototype.da.call(this);this.l&&this.l.cancel()};
g.k.qB=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.tc();var b=this.i;this.i=g.Ya(this.X.zl(a).i);b!==this.i&&this.L&&this.L()};
g.k.reset=function(){this.B=new a2;this.l&&(this.l.cancel(),this.l=null)};
g.k.JE=function(){this.na();var a;if(a=null!=this.i)a=this.i,a=a.i.Rk(a);!a||this.l||this.i&&30<this.i.startTime-this.player.getCurrentTime()||(a=this.i,a=a.i.Yp(a),a.i[0].duration?(this.B.contains(a.i[0].va)||dFa(this,a),this.i=g.Ya(a.i)):!g.S(this.W.experiments,"force_caption_seek_for_live_killswitch")&&this.i&&this.i.B&&this.i.B+this.player.tc()<this.player.getCurrentTime()&&this.seekTo(this.player.getCurrentTime()));this.J.start()};
g.u(c2,Z1);g.k=c2.prototype;g.k.pu=function(a,b,c){var d=this;this.Ik();b=fFa(this,a.getId());b||(b=a.languageCode,b=this.i.isManifestless?gFa(this,b,"386"):gFa(this,b));if(b){var e=1E3*(b.index.Wt(b.index.fi())-b.index.kf(b.index.fi()));this.u=new b2(new g.Ay,this.G,b,function(f,h){c(f,a,h,e)},this.I||g.rw(b.info),function(){d.u&&d.u.reset();
d.B=!0})}};
g.k.oG=function(){var a=this.B;this.B=!1;return a};
g.k.qu=function(a){var b=this.I?[new g.PH({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.PH({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.i.isManifestless?eFa(this,"386"):eFa(this);b=g.q(b);for(var c=b.next();!c.done;c=b.next())Y1(this.l,c.value);a()};
g.k.Ik=function(){this.u&&(this.u.dispose(),this.u=null)};
g.k.No=function(){return""};
g.u(d2,Z1);d2.prototype.pu=function(a,b,c){var d=this;this.na();b=this.No(a,b);this.Ik();this.i=g.Yp(b,{format:"RAW",onSuccess:function(e){d.i=null;c(e.responseText,a)},
withCredentials:!0})};
d2.prototype.qu=function(a){var b=this,c=this.u,d={type:"list",tlangs:1,v:this.videoId,vssids:1};this.gE&&(d.asrs=1);c=g.Ip(c,d);this.Ik();this.i=g.Yp(c,{format:"RAW",onSuccess:function(e){b.i=null;if((e=e.responseXML)&&e.firstChild){for(var f=e.getElementsByTagName("track"),h=0;h<f.length;h++){var l=f[h],m=l.getAttribute("lang_code"),n=l.getAttribute("lang_translated"),p=l.getAttribute("name"),r=l.getAttribute("kind"),t=l.getAttribute("id"),w="true"===l.getAttribute("lang_default"),x="true"===l.getAttribute("cantran");
l=l.getAttribute("vss_id");Y1(b.l,new g.PH({languageCode:m,languageName:n,name:p,kind:r,id:t,is_servable:!0,is_translateable:x,vss_id:l,is_default:w}))}e=e.getElementsByTagName("target");f=e.length;for(h=0;h<f;h++)m={languageCode:e[h].getAttribute("lang_code"),languageName:e[h].getAttribute("lang_translated"),languageOriginal:e[h].getAttribute("lang_original"),id:e[h].getAttribute("id"),isDefault:"true"===e[h].getAttribute("lang_default")},b.B[m.languageCode]=m.languageName,b.C.push(m)}a()},
withCredentials:!0})};
d2.prototype.No=function(a,b){var c=this.u,d={v:this.videoId,type:"track",lang:a.languageCode,name:a.getName(),kind:a.kind,fmt:b};a.translationLanguage&&(d.tlang=W1(a));return c=g.Ip(c,d)};
d2.prototype.Ik=function(){this.i&&this.i.abort()};
var q2=/^#(?:[0-9a-f]{3}){1,2}$/i,iFa=/#(.)(.)(.)/,hFa=/^#(?:[0-9a-f]{3}){1,2}$/i;var kFa=["left","right","center","justify"];g.u(f2,g.W);g.k=f2.prototype;g.k.qJ=function(a,b){var c=g.Ig(this.element,this.element.parentElement);this.Ha=a-c.x;this.Ka=b-c.y;g.M(this.element,"ytp-dragging")};
g.k.pJ=function(a,b){var c=g.Kg(this.element),d=a-this.Ha-.02*this.playerWidth,e=b-this.Ka-.02*this.playerHeight,f=(d+c.width/2)/this.maxWidth*3;f=Math.floor(g.Zd(f,0,2));var h=(e+c.height/2)/this.za*3;h=Math.floor(g.Zd(h,0,2));var l=f+3*h;d=(d+f/2*c.width)/this.maxWidth;d=100*g.Zd(d,0,1);c=(e+h/2*c.height)/this.za;c=100*g.Zd(c,0,1);this.l.params.ai=l;this.l.params.Hi=c;this.l.params.bh=d;this.i.ai=l;this.i.Hi=c;this.i.bh=d;this.KG()};
g.k.oJ=function(){g.rn(this.element,"ytp-dragging")};
g.k.KG=function(){this.Fp(this.C)};
g.k.Db=function(){return this.type};
g.k.Fp=function(a){var b=Math.min(this.FD(),this.maxWidth),c=this.ED(),d="";3===this.l.params.Ue&&(d="rotate(180deg)");g.ug(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.Yw(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.i.bh+2;d=this.i.ai;switch(d){case 0:case 3:case 6:(b=this.i.Hc.fontSizeIncrement)&&0<b&&2!==this.i.Ue&&3!==
this.i.Ue&&(e=Math.max(e/(1+2*b),2));a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.B.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.i.Hi+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.ug(this.element,
a)};
g.k.Yw=function(a){var b;for(b=0;b<a.length&&a[b]===this.C[b];b++);if(this.ca||this.C.length>b)b=0,this.ca=!1,this.C=[],this.I=this.ia=this.ea=null,g.Ee(this.B);for(;b<a.length;b++)oFa(this,a[b])};
g.k.FD=function(){return 0};
g.k.ED=function(){return 0};
g.k.toString=function(){return g.W.prototype.toString.call(this)};g.u(g2,f2);g2.prototype.Yw=function(a){var b=this.l.i;f2.prototype.Yw.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.i===e)var d=f;else{d={};g.Qa(d,c.i);g.Qa(d,YFa);var e=c.i;var f=d}oFa(this,c,d)}};
var YFa={RL:!0};g.u(h2,f2);g.k=h2.prototype;g.k.KG=function(){this.ma.Ug()};
g.k.PO=function(){g.rn(this.element,"ytp-rollup-mode");this.Fp(this.Xa,!0)};
g.k.ED=function(){return this.u?this.X:this.L};
g.k.FD=function(){return this.u?this.L:this.X};
g.k.Fp=function(a,b){this.Xa=a;if(this.l.params.Ck){for(var c=0,d=0;d<this.C.length&&c<a.length;d++)this.C[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.C.concat(a.slice(c)));this.Qa=this.X;this.L=this.X=0;f2.prototype.Fp.call(this,a);rFa(this,b)}f2.prototype.Fp.call(this,a)};g.u(i2,g.pG);i2.prototype.toString=function(){return g.pG.prototype.toString.call(this)};g.u(j2,g.pG);j2.prototype.toString=function(){return g.pG.prototype.toString.call(this)};
var k2=0;g.u(l2,g.J);l2.prototype.u=function(){return[]};
l2.prototype.reset=function(){};g.u(m2,l2);m2.prototype.reset=function(){this.L={};this.l=this.i=null;this.J=!0};
m2.prototype.u=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.q(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1===d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.q(e),c=e.next();!c.done;c=e.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var h=this.B,l={},m=c.getAttribute("p");m&&g.Qa(l,this.B[m]);m=o2(c,"b");null!=m&&
(l.bold=m);m=o2(c,"i");null!=m&&(l.ki=m);m=o2(c,"u");null!=m&&(l.underline=m);m=p2(c,"et");null!=m&&(l.charEdgeStyle=m);m=p2(c,"of");null!=m&&(l.offset=m);m=r2(c,"bc");null!=m&&(l.background=m);m=r2(c,"ec");null!=m&&(l.lx=m);m=r2(c,"fc");null!=m&&(l.color=m);m=p2(c,"fs");null!=m&&0!==m&&(l.fontFamily=m);m=n2(c,"sz");void 0!==m&&(l.fontSizeIncrement=m/100-1);m=n2(c,"bo");void 0!==m&&(l.backgroundOpacity=m/255);m=n2(c,"fo");void 0!==m&&(l.textOpacity=m/255);m=p2(c,"rb");null!=m&&10!==m&&0!==m&&(l.Cd=
10<m?m-1:m);c=p2(c,"hg");null!=c&&(l.bE=c);h[d]=l;break;case "ws":d=c.getAttribute("id");this.X[d]=vFa(this,c);break;case "wp":d=c.getAttribute("id"),this.W[d]=wFa(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.q(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1===d.nodeType)switch(d.tagName){case "w":this.i=xFa(this,d,e,!1);(d=this.L[this.i.id])&&d.end>this.i.start&&(d.end=this.i.start);this.L[this.i.id]=this.i;c.push(this.i);break;case "p":var n=e;h=[];l=d.getAttribute("w")||this.I;m=!!o2(d,
"a");n=(n2(d,"t")||0)+n;var p=n2(d,"d")||5E3;m||(!this.J&&this.l&&this.l.windowId===l&&this.l.end>n&&(this.l.end=n),this.l&&"\n"===this.l.text&&(this.l.text=""));var r=m?6:5,t=d.getAttribute("p");t=t?this.B[t]:null;var w=Array.from(d.childNodes);w.length&&(this.J=null!=d.getAttribute("d"));for(var x=0;x<w.length;x++){var y=w[x],F=void 0;0<x&&(m=!0);var E=void 0;1===y.nodeType&&(E=y);if(E&&"s"===E.tagName){if((y=(y=E.getAttribute("p"))?this.B[y]:null)&&y.Cd&&(1===y.Cd?(y=w.slice(x,x+4),4===y.length&&
(F=uFa(n,p,l,m,r,y,this.B),x+=3)):F=uFa(n,p,l,m,r,[E],this.B)),!F){var G=E;F=n;E=p;y=l;var I=m,H=r,Aa=G.textContent?G.textContent:"",oa=G.getAttribute("p");oa=oa?this.B[oa]:null;G=n2(G,"t")||0;F=new i2(F+G,E-G,H,y,Aa,I,oa)}}else F=new i2(n,p,r,l,y.textContent||"",m,t);h.push(F);this.l=F}if(0<h.length)for(h[0].windowId===this.I&&(this.i=xFa(this,d,e,!0),c.push(this.i)),d=g.q(h),h=d.next();!h.done;h=d.next())h=h.value,h.windowId=this.i.id,this.i.i.push(h),c.push(h)}e=c}else e=[];return e};var ZFa=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.u(s2,l2);s2.prototype.reset=function(){this.l.clear()};
s2.prototype.u=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens)for(var d=0,e=g.q(c.pens),f=e.next();!f.done;f=e.next()){f=f.value;var h={},l=f.pParentId;l&&Object.assign(h,this.i.get(l));f.bAttr&&(h.bold=!0);f.iAttr&&(h.ki=!0);f.uAttr&&(h.underline=!0);l=f.ofOffset;null!=l&&(h.offset=l);void 0!==f.szPenSize&&(h.fontSizeIncrement=f.szPenSize/100-1);l=f.etEdgeType;null!=l&&(h.charEdgeStyle=l);void 0!==f.ecEdgeColor&&(h.lx=t2(f.ecEdgeColor));l=f.fsFontStyle;null!=l&&0!==l&&(h.fontFamily=l);
void 0!==f.fcForeColor&&(h.color=t2(f.fcForeColor));void 0!==f.foForeAlpha&&(h.textOpacity=f.foForeAlpha/255);void 0!==f.bcBackColor&&(h.background=t2(f.bcBackColor));void 0!==f.boBackAlpha&&(h.backgroundOpacity=f.boBackAlpha/255);(l=f.rbRuby)&&10!==l&&(h.Cd=10<l?l-1:l,h.Fi=ZFa.get(h.Cd));f.hgHorizGroup&&(h.bE=f.hgHorizGroup);this.i.set(d++,h)}if(c.wsWinStyles)for(d=0,e=g.q(c.wsWinStyles),f=e.next();!f.done;f=e.next())f=f.value,h={},(l=f.wsParentId)?Object.assign(h,this.C.get(l)):Object.assign(h,
this.I),void 0!==f.mhModeHint&&(h.ip=f.mhModeHint),void 0!==f.juJustifCode&&(h.textAlign=f.juJustifCode),void 0!==f.pdPrintDir&&(h.Ue=f.pdPrintDir),void 0!==f.sdScrollDir&&(h.oA=f.sdScrollDir),void 0!==f.wfcWinFillColor&&(h.windowColor=t2(f.wfcWinFillColor)),void 0!==f.wfoWinFillAlpha&&(h.windowOpacity=f.wfoWinFillAlpha/255),this.C.set(d++,h);if(c.wpWinPositions)for(d=0,e=g.q(c.wpWinPositions),f=e.next();!f.done;f=e.next())f=f.value,h={},(l=f.wpParentId)&&Object.assign(h,this.B.get(l)),void 0!==f.ahHorPos&&
(h.bh=f.ahHorPos),void 0!==f.apPoint&&(h.ai=f.apPoint),void 0!==f.avVerPos&&(h.Hi=f.avVerPos),void 0!==f.ccCols&&(h.fl=f.ccCols),void 0!==f.rcRows&&(h.Ck=f.rcRows),this.B.set(d++,h);if(c.events)for(d=[],c=g.q(c.events),e=c.next();!e.done;e=c.next()){var m=e.value;e=(m.tStartMs||0)+b;f=m.dDurationMs||0;if(m.id)h=String(m.id),e=yFa(this,m,e,f,h),d.push(e),this.l.set(h,e);else{m.wWinId?h=m.wWinId.toString():(h="_"+k2++,l=yFa(this,m,e,f,h),d.push(l),this.l.set(h,l));0===f&&(f=5E3);l=this.l.get(h);var n=
!!m.aAppend,p=n?6:5,r=m.segs,t=null;m.pPenId&&(t=this.i.get(m.pPenId));for(m=0;m<r.length;m++){var w=r[m],x=w.utf8;if(x){var y=w.tOffsetMs||0,F=null;w.pPenId&&(F=this.i.get(w.pPenId));if(2===(null!=l.params.ip?l.params.ip:1<l.i.length?1:0)&&n&&"\n"===x)continue;if(w=F&&1===F.Cd)if(w=m,w+3>=r.length||!r[w+1].pPenId||!r[w+2].pPenId||!r[w+3].pPenId)w=!1;else{var E=r[w+1].pPenId;(E=this.i.get(E))&&E.Cd&&2===E.Cd?(E=r[w+2].pPenId,E=this.i.get(E),!E||!E.Cd||3>E.Cd?w=!1:(E=r[w+3].pPenId,w=(E=this.i.get(E))&&
E.Cd&&2===E.Cd?!0:!1)):w=!1}if(w){y=r[m+1].utf8;w=r[m+3].utf8;E=r[m+2].utf8;var G=this.i.get(r[m+2].pPenId);x=tFa(x,y,E,w,G);n=new i2(e,f,p,h,x,n,F);m+=3}else n=new i2(e+y,f-y,p,l.id,x,n,F||t);n&&(d.push(n),l.i.push(n))}n=!0}}}else d=[];return d};v2.prototype.clear=function(){this.u=this.time=this.mode=0;this.i=[];this.reset()};
v2.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var zFa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];w2.prototype.set=function(a){this.type=a};
w2.prototype.get=function(){return this.type};
x2.prototype.clear=function(){this.state=0};
x2.prototype.update=function(){this.state=2===this.state?1:0};
x2.prototype.isValid=function(){return 0!==this.state};
x2.prototype.matches=function(a,b){return this.isValid()&&a===this.Om&&b===this.Zk};
EFa.prototype.reset=function(){this.timestamp=this.i=0};
y2.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.u[b][c].timestamp=a};
y2.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.u[b][c];a=0===d.i?a+"_":a+String.fromCharCode(d.i)}a+="\n"}return a};
y2.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.u[b][c].reset();this.B=a;this.i=0;this.l=this.row=1};
var FFa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],GFa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],HFa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],IFa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];E2.prototype.reset=function(a,b){this.C=b;this.style.set(2);this.l=this.I;this.B=this.J;this.i=this.l;var c=(a<<2)+(b<<1);this.I.reset(c);this.J.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
u2.prototype.reset=function(a){this.C=a;this.l.clear();this.B=this.u;this.u.reset(a,0);this.I.reset(a,1)};NFa.prototype.B=function(){};g.u(G2,NFa);G2.prototype.B=function(a,b,c,d,e){if(c<d){var f="_"+k2++;c=c/1E3-this.I;d=d/1E3-this.I;a=new j2(c,d-c,5,f,{textAlign:0,ai:0,bh:2.5*b,Hi:5.33*a});e=new i2(c,d-c,5,f,e);this.l.push(a);this.l.push(e)}};
g.u(J2,l2);J2.prototype.u=function(a){a=new G2(a,a.byteLength,this.l);if(OFa(a)){for(;a.byteOffset<a.i.byteLength;)for(0===a.version?a.u=I2(a)*(1E3/45):1===a.version&&(a.u=4294967296*I2(a)+I2(a)),a.C=H2(a);0<a.C;a.C--){var b=H2(a),c=H2(a),d=H2(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.i,b.i.push({time:a.u,type:this.track,HC:c,IC:d,order:b.i.length}))}DFa(this.i,a);return a.l}return[]};
J2.prototype.reset=function(){this.i.clear()};g.u(L2,l2);
L2.prototype.u=function(a,b){for(var c=[],d=a.split($Fa),e=1;e<d.length;e++){var f=d[e],h=b;if(""!==f&&!aGa.test(f)){var l=Z2.exec(f);if(l&&4<=l.length){var m=M2(l[1]),n=M2(l[2])-m;m+=h;var p=(l=l[3])?l.split(" "):[];l={};var r=null,t="",w=null,x="";l.textAlign=2;p=g.q(p);for(var y=p.next();!y.done;y=p.next())if(y=y.value.split(":"),2===y.length){var F=y[1];switch(y[0]){case "line":y=F.split(",");y[0].endsWith("%")&&(r=y[0],l.Hi=Number.parseInt(r,10),2===y.length&&(t=y[1].trim()));break;case "position":y=
F.split(",");w=y[0];l.bh=Number.parseInt(w,10);2===y.length&&(x=y[1].trim());break;case "align":switch(F){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}r||(l.Hi=100,t||(t="end"));if(!w)switch(l.textAlign){case 0:l.bh=0;break;case 1:l.bh=100;break;default:l.bh=50}r=0;switch(t){case "center":r+=3;break;case "end":r+=6;break;default:r+=0}switch(x){case "line-left":r+=0;break;case "center":r+=1;break;case "line-right":r+=2;break;default:switch(l.textAlign){case 0:r+=
0;break;case 2:r+=1;break;case 1:r+=2}}l.ai=0>r||8<r?7:r;f=f.substring(Z2.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");x=l;l=f;f={};if(0>l.indexOf("<")&&0>l.indexOf("&"))h=QFa(m,n,5,x),n=new i2(m,n,5,h.id,l,!1,g.Mb(f)?void 0:f),c.push(h),c.push(n),h.i.push(n);else for(t=l.split(bGa),1===t.length?(l=5,x=QFa(m,n,l,x)):(r=l=6,x=Object.assign({fl:32},x),x=new j2(m,n,r,"_"+k2++,x)),c.push(x),r=m,w=0;w<t.length;w++)p=t[w],0===w%2?(y=g.F_("<html>"+p+"</html>"),y.getElementsByTagName("parsererror").length?
(F=y.createElement("span"),F.appendChild(y.createTextNode(p))):F=y.firstChild,PFa(this,r,n-(r-m),l,x,0<w,F,f,c)):r=M2(p)+h}Z2.lastIndex=0}}return c};
var aGa=/^NOTE/,$Fa=/(?:\r\n|\r|\n){2,}/,Z2=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),bGa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.u(N2,g.J);N2.prototype.clear=function(){this.i&&this.i.dispose();this.i=null};
N2.prototype.reset=function(){this.i&&this.i.reset()};
N2.prototype.da=function(){g.J.prototype.da.call(this);this.clear()};var Y2={windowColor:"#080808",windowOpacity:0,textAlign:2,ai:7,bh:50,Hi:100,Hc:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.u(Q2,g.iO);g.k=Q2.prototype;g.k.da=function(){if(this.I||this.ea){var a=this.G.nd();a&&!a.na()&&a.yq()}else XFa(this,!1);g.iO.prototype.da.call(this)};
g.k.Mn=function(){if(this.Ia)return this.I||this.ea;var a=this.player.getAudioTrack().captionsInitialState;return"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===a?!0:"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===a?S2(this):R2(this)||S2(this)?!0:TFa(this)};
g.k.load=function(){var a=this;g.iO.prototype.load.call(this);var b=!g.S(this.l.experiments,"web_player_captions_track_list_changed_killswitch");this.J=this.player.getAudioTrack();if(this.u)this.i&&(this.za.clear(),this.I?UFa(this,!0):3!==this.player.getPresentingPlayerType()&&this.u.pu(this.i,"json3",function(d,e,f,h){if(d){a.u.oG()&&(a.Y=[],a.G.Qe("captions"),U1(a.ca),a.za.reset());var l=a.za;f=f||0;h=h||0;if(l.l.Z("html5_disable_rawcc_killswitch")){if("string"!==typeof d){var m=new DataView(d);
8<=m.byteLength&&1718909296===m.getUint32(4)&&(m=g.fv(m,0,1835295092),d=d.slice(m.dataOffset,m.dataOffset+m.size),K2(d)||(d=g.Se(new Uint8Array(d))))}}else"string"===typeof d||K2(d)||(m=new DataView(d),d=8>=m.byteLength||1718909296!==m.getUint32(4)?"":(m=g.fv(m,0,1835295092))&&m.size?g.Se(new Uint8Array(d.slice(m.dataOffset,m.dataOffset+m.size))):"");if(d)try{if("string"!==typeof d){var n=d,p=f,r=h;if(!K2(n))throw Error("Invalid binary caption track data");l.i||(l.i=new J2(r,e));var t=l.i.u(n,p)}else{if("WEBVTT"===
d.substring(0,6))e=d,r=f,l.i||(l.i=new L2),p=l.i.u(e,r),.01>Math.random()&&g.jt(Error("Deprecated subtitles format in web player: WebVTT")),n=p;else b:{p=d;if("{"===p[0])try{l.i||(l.i=new s2(SFa(e)));n=l.i.u(p,f);break b}catch(G){g.it(G);n=[];break b}r=g.F_(p);if(!r||!r.firstChild){var w=Error("Invalid caption track data");w.params=p;throw w;}if("timedtext"===r.firstChild.tagName){if(3===Number(r.firstChild.getAttribute("format"))){l.i||(l.i=new m2(SFa(e),l.l));n=l.i.u(r,f);break b}var x=Error("Unsupported subtitles format in web player (Format2)");
x.params=p;throw x;}if("transcript"===r.firstChild.tagName){var y=Error("Unsupported subtitles format in web player (Format1)");y.params=p;throw y;}var F=Error("Invalid caption track data");F.params=p;throw F;}t=n}var E=t}catch(G){g.it(G),l.clear(),E=[]}else E=[];a.player.Kd(E);!a.X||a.ea||V2(a)||g.eD(a.l)||g.WC(a.l)||(g.ln(a.ga),E=sFa({ai:0,bh:5,Hi:5,Ck:2,textAlign:0,Ue:0,lang:"en-GB"}),a.la=[E],l=["Click "," for settings"],a.Da||(t=new g.QL(g.fM()),g.K(a,t),a.Da=t.element),t=E.end-E.start,(e=g.QH(a.i))&&
a.la.push(new i2(E.start,t,0,E.id,e)),a.la.push(new i2(E.start,t,0,E.id,l[0]),new i2(E.start,t,0,E.id,a.Da,!0),new i2(E.start,t,0,E.id,l[1],!0)),a.player.Kd(a.la),g.kn(a.ga));!a.X||a.ea||V2(a)||(g.vD(a.l)?(0,g.e0)(!0):W2(a,"module-enabled",!0),a.J&&(a.J.C=a.i),a.player.Un());a.X=!1}}),!b||this.I||this.ea||V2(this)||this.player.xa("captionschanged",V1(this.i))),b||(this.i&&!V2(this)?this.player.xa("captionschanged",V1(this.i)):this.player.xa("onCaptionsTrackListChanged"));
else{var c;this.Ha?c=new c2(this.videoData.i,this.player):this.Wa?c=new $1(this.l,this.videoData,this.player.getAudioTrack()):c=new d2(this.videoData.oh,this.videoData.videoId,this.videoData.captionsLanguagePreference||this.l.captionsLanguagePreference||g.YI(this.videoData,"yt:cc_default_lang")||this.l.kd,this.videoData.NA,this.l);this.u=c;g.K(this,this.u);c.qu(function(){var d=a.player.getAudioTrack().captionsInitialState,e;"CAPTIONS_INITIAL_STATE_UNKNOWN"===d?R2(a)||a.X||TFa(a)?e=U2(a,a.X):S2(a)&&
(e=T2(a)):"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===d?e=U2(a,a.X):"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===d&&S2(a)&&(e=T2(a));if(a.I||a.ea){var f=X1(a.u.l,!0);d=[];for(var h=0;h<f.length;h++){var l=f[h],m=g.Ce("TRACK");m.setAttribute("kind","subtitles");m.setAttribute("label",g.QH(l));m.setAttribute("srclang",W1(l));m.setAttribute("id",l.toString());a.ea||m.setAttribute("src",a.u.No(l,"vtt"));l===e&&m.setAttribute("default","1");d.push(m)}e=a.G.nd();e.mq(d);e=e.le();a.Ka&&a.ia.N(e.textTracks,"change",
a.tP)}else!a.i&&e&&X2(a,e),a.player.xa("onCaptionsTrackListChanged"),a.player.xa("onApiChange")})}};
g.k.unload=function(){this.I&&this.i?UFa(this,!1):(this.ga&&g.ln(this.ga),this.player.Qe("captions"),this.Y=[],this.u&&this.u.Ik(),this.za.clear(),this.L&&this.player.Kd(this.L),this.GA());g.iO.prototype.unload.call(this);this.player.Un();this.player.xa("captionschanged",{})};
g.k.create=function(){this.Mn()&&this.load()};
g.k.tP=function(){for(var a=this.G.nd().le().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=a[c].id;var d=X1(this.u.l,!0);for(var e=0;e<d.length;e++)if(d[e].toString()===b){b=d[e];break a}b=null}(this.loaded?this.i:null)!==b&&X2(this,b,!0)};
g.k.cR=function(){!this.i&&this.I||this.unload()};
g.k.Ad=function(a){this.Y.push(a);U1(this.ca)};
g.k.nf=function(a){g.ib(this.Y,a);this.u instanceof c2&&this.u.I&&this.player.jg([a]);U1(this.ca)};
g.k.cQ=function(a){if(a instanceof j2){var b=this.W[a.id];b&&b.l!==a&&(b.dispose(),delete this.W[a.id],b=null);b||(b=VFa(this,a))&&(this.W[a.id]=b)}else b=a.windowId,this.ma[b]||(this.ma[b]=[]),this.ma[b].push(a)};
g.k.jQ=function(){WFa(this,this.la);this.la=null};
g.k.uH=function(){var a=this;this.ca.stop();g.Nb(this.ma);this.Y.sort(g.rG);var b=this.Y;if(this.L){var c=g.He(b,function(d){return-1===this.L.indexOf(d)},this);
c.length&&(b=c)}g.yb(b,this.cQ,this);g.Ab(this.W,function(d,e){a.ma[e]?(d.element.parentNode||(d instanceof h2||d instanceof g2||g.Db(a.W,function(f,h){h!==e&&f.l.params.ai===d.l.params.ai&&f.l.params.bh===d.l.params.bh&&f.l.params.Hi===d.l.params.Hi&&(f.dispose(),delete a.W[h]);return h===e},a),g.ZN(a.player,d.element,4)),d.Fp(a.ma[e])):(d.dispose(),delete a.W[e])},this)};
g.k.nQ=function(){O2(this,{},!0);g.S(this.l.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.xa("captionssettingschanged")};
g.k.rL=function(){var a=Y2.Hc;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.ki?3:a.bold?1:a.ki?2:0,textOpacity:a.textOpacity,windowColor:Y2.windowColor,windowOpacity:Y2.windowOpacity};var b=P2(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.CH=function(a,b){var c={};g.Qa(c,P2(this,"display-settings"));g.Qa(c,a);O2(this,c,b);this.player.xa("captionssettingschanged")};
g.k.GA=function(){!this.I&&this.loaded&&(g.Ab(this.W,function(a,b){a.dispose();delete this.W[b]},this),this.uH())};
g.k.Ie=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Zd(b,-2,4);this.CH({fontSizeIncrement:c});return c;case "reload":b&&!this.I&&X2(this,this.i,!0);break;case "stickyLoading":void 0!==b&&this.l.u&&(g.vD(this.l)?(0,g.e0)(!!b):W2(this,"module-enabled",!!b));break;case "track":if(!this.u)return{};if(b){if(this.I)break;if(!g.Ma(b))break;if(g.Mb(b)){X2(this,null,!0);break}for(var d=X1(this.u.l,!0),e=0;e<d.length;e++){var f=d[e];f.languageCode!==b.languageCode||c&&f.languageName!==
b.languageName||(c=b.translationLanguage?$Ea(f,b.translationLanguage):f)}!c||c===this.i&&this.loaded||(d=(0,g.Foa)(),e=W1(c),d.length&&e===d[d.length-1]||(d.push(e),(0,g.YCa)(d)),X2(this,c,!0))}else return this.loaded&&this.i&&!V2(this)?V1(this.i):{};return"";case "tracklist":return this.u?g.Jc(X1(this.u.l,!(!b||!b.includeAsr)),function(h){return V1(h)}):[];
case "translationLanguages":return this.u?this.u.C.map(function(h){return Object.assign({},h)}):[];
case "sampleSubtitles":this.I||void 0===b||XFa(this,!!b)}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.l.u&&a.push("stickyLoading");return a};
g.k.my=function(){var a=this.i;return a?{cc:a.vssId}:{}};
g.k.QQ=function(){this.loaded&&this.i&&!V2(this)?(g.vD(this.l)?(0,g.e0)(!1):W2(this,"module-enabled",!1),this.unload(),S2(this,!0)&&X2(this,T2(this),!1)):X2(this,V2(this)||!this.i?U2(this,!0):this.i,!0)};
g.k.ZM=function(){var a=V2(this);S2(this,a)?X2(this,this.player.getAudioTrack().l,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.Mn()&&(a?X2(this,U2(this),!1):this.load()))};g.oO.captions=Q2;})(_yt_player);
