(function(g){var window=this;var HGa=function(a,b){a.xa("onAutonavCoundownStarted",b)},C3=function(a,b,c){var d=b.Na();
g.N(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.ze(c?c:"mqdefault.jpg");var f=null,h=null;b instanceof g.vI&&(b.lengthText?(f=b.lengthText||null,h=b.ou||null):b.lengthSeconds&&(f=g.zM(b.lengthSeconds),h=g.zM(b.lengthSeconds,!0)));var l=!!e;e=l&&"RD"===(new g.cO(e.substr(0,2),e.substr(2))).type;var m=b instanceof g.vI?b.isLivePlayback:null,n=b instanceof g.vI?b.isUpcoming:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:
b.author,aria_label:b.nq||g.xK("Watch $TITLE",{TITLE:b.title}),duration:f,timestamp:h,url:b.Bl(),is_live:m,is_upcoming:n,is_list:l,is_mix:e,background:c?"background-image: url("+c+")":"",views_and_publish_time:d.shortViewCount?d.shortViewCount+" \u2022 "+d.publishedTimeText:d.publishedTimeText,autoplayAlternativeHeader:b.rq};b instanceof g.dO&&(d.playlist_length=b.length);a.update(d)},D3=function(a){var b=a.T(),c=b.l;
g.W.call(this,{D:"a",K:"ytp-autonav-suggestion-card",U:{href:"{{url}}",target:c?b.C:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},S:[{D:"div",ka:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],U:{style:"{{background}}"},S:[{D:"div",U:{"aria-label":"{{timestamp}}"},ka:["ytp-autonav-timestamp"],ba:"{{duration}}"},{D:"div",ka:["ytp-autonav-live-stamp"],ba:"Live"},{D:"div",
ka:["ytp-autonav-upcoming-stamp"],ba:"Upcoming"},{D:"div",K:"ytp-autonav-list-overlay",S:[{D:"div",K:"ytp-autonav-mix-text",ba:"Mix"},{D:"div",K:"ytp-autonav-mix-icon"}]}]},{D:"div",ka:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],ba:"{{title}}"},{D:"div",ka:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],ba:"{{author}}"},{D:"div",ka:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],ba:"{{views_and_publish_time}}"}]});this.G=a;this.suggestion=
null;this.i=c;this.ya("click",this.onClick);this.ya("keypress",this.l)},F3=function(a,b){b=void 0===b?!1:b;
g.W.call(this,{D:"div",K:"ytp-autonav-endscreen-countdown-container"});var c=this;this.C=b;this.l=0;var d=a.T(),e=d.l;this.G=a;this.suggestion=null;this.i=new g.W({D:"div",K:"ytp-autonav-endscreen-upnext-container",U:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},S:[{D:"div",K:"ytp-autonav-endscreen-upnext-header"},{D:"div",K:"ytp-autonav-endscreen-upnext-alternative-header",ba:"{{autoplayAlternativeHeader}}"},
{D:"a",K:"ytp-autonav-endscreen-link-container",U:{href:"{{url}}",target:e?d.C:""},S:[{D:"div",K:"ytp-autonav-endscreen-upnext-thumbnail",U:{style:"{{background}}"},S:[{D:"div",U:{"aria-label":"{{timestamp}}"},ka:["ytp-autonav-timestamp"],ba:"{{duration}}"},{D:"div",ka:["ytp-autonav-live-stamp"],ba:"Live"},{D:"div",ka:["ytp-autonav-upcoming-stamp"],ba:"Upcoming"}]},{D:"div",K:"ytp-autonav-endscreen-video-info",S:[{D:"div",K:"ytp-autonav-endscreen-premium-badge"},{D:"div",K:"ytp-autonav-endscreen-upnext-title",
ba:"{{title}}"},{D:"div",K:"ytp-autonav-endscreen-upnext-author",ba:"{{author}}"},{D:"div",K:"ytp-autonav-view-and-date",ba:"{{views_and_publish_time}}"},{D:"div",K:"ytp-autonav-author-and-view",ba:"{{author_and_views}}"}]}]}]});g.K(this,this.i);this.i.fa(this.element);e||this.N(this.i.ha("ytp-autonav-endscreen-link-container"),"click",this.GB);this.G.Ib(this.element,this,115127);this.G.Ib(this.i.ha("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.W({D:"div",K:"ytp-autonav-overlay"});
g.K(this,this.overlay);this.overlay.fa(this.element);this.u=new g.W({D:"div",K:"ytp-autonav-endscreen-button-container"});g.K(this,this.u);this.u.fa(this.element);this.cancelButton=new g.W({D:"button",ka:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button"],U:{"aria-label":"Cancel autoplay"},ba:"Cancel"});g.K(this,this.cancelButton);this.cancelButton.fa(this.u.element);this.cancelButton.ya("click",this.AJ,this);this.G.Ib(this.cancelButton.element,this,115129);this.playButton=
new g.W({D:"a",ka:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button"],U:{href:"{{url}}",role:"button","aria-label":"Play next video"},ba:"Play now"});g.K(this,this.playButton);this.playButton.fa(this.u.element);this.playButton.ya("click",this.GB,this);this.G.Ib(this.playButton.element,this,115130);this.B=new g.L(function(){E3(c)},500);
g.K(this,this.B);this.FB();this.N(a,"autonavvisibility",this.FB)},E3=function(a){var b=G3(a),c=Math.min(a.l?Date.now()-a.l:0,b);
H3(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Zg()?a.select(!0):a.Zg()&&a.B.start()},G3=function(a){var b=a.G.bn();
return 0<=b?b:g.R(a.G.T().experiments,"autoplay_time")||1E4},H3=function(a,b){b=void 0===b?-1:b;
var c=a.i.ha("ytp-autonav-endscreen-upnext-header");g.Ee(c);if(0<=b){var d=String(b),e="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],f="Up next in $SECONDS".indexOf(e);if(0<=f){c.appendChild(g.De("Up next in $SECONDS".slice(0,f)));var h=g.Ce("span");g.on(h,"ytp-autonav-endscreen-upnext-header-countdown-number");g.Ke(h,d);c.appendChild(h);c.appendChild(g.De("Up next in $SECONDS".slice(f+e.length)));return}}g.Ke(c,"Up next")},I3=function(a,b){g.W.call(this,{D:"div",
ka:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},K3=function(a){g.W.call(this,{D:"div",
ka:["ytp-upnext","ytp-player-content"],U:{"aria-label":"{{aria_label}}"},S:[{D:"div",K:"ytp-cued-thumbnail-overlay-image",U:{style:"{{background}}"}},{D:"span",K:"ytp-upnext-top",S:[{D:"span",K:"ytp-upnext-header",ba:"Up Next"},{D:"span",K:"ytp-upnext-title",ba:"{{title}}"},{D:"span",K:"ytp-upnext-author",ba:"{{author}}"}]},{D:"a",K:"ytp-upnext-autoplay-icon",U:{role:"button",href:"{{url}}","aria-label":"Play next video"},S:[{D:"svg",U:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
S:[{D:"circle",K:"ytp-svg-autoplay-circle",U:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{D:"circle",K:"ytp-svg-autoplay-ring",U:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{D:"path",K:"ytp-svg-fill",U:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{D:"span",K:"ytp-upnext-bottom",S:[{D:"span",K:"ytp-upnext-cancel"},{D:"span",K:"ytp-upnext-paused",
ba:"Auto-play is paused"}]}]});this.api=a;this.cancelButton=null;this.C=this.ha("ytp-svg-autoplay-ring");this.u=this.notification=this.i=this.suggestion=null;this.B=new g.L(this.vt,5E3,this);this.l=0;var b=this.ha("ytp-upnext-cancel");this.cancelButton=new g.W({D:"button",ka:["ytp-upnext-cancel-button","ytp-button"],U:{tabindex:"0","aria-label":"Cancel autoplay"},ba:"Cancel"});g.K(this,this.cancelButton);this.cancelButton.ya("click",this.BJ,this);this.cancelButton.fa(b);this.cancelButton&&this.api.Ib(this.cancelButton.element,
this,115129);g.K(this,this.B);this.api.Ib(this.element,this,18788);b=this.ha("ytp-upnext-autoplay-icon");this.N(b,"click",this.CJ);this.api.Ib(b,this,115130);this.HB();this.N(a,"autonavvisibility",this.HB);this.N(a,"mdxnowautoplaying",this.UN);this.N(a,"mdxautoplaycanceled",this.VN);this.N(a,"mdxautoplayupnext",this.BH);J3(this)&&(a=(a=g.VN(this.api.Ua()))?a.qL():null)&&this.BH(a);g.N(this.element,"ytp-upnext-mobile",this.api.T().i)},J3=function(a){return 3===a.api.getPresentingPlayerType()},IGa=
function(a,b){return b?b:0<=a.api.bn()?a.api.bn():g.R(a.api.T().experiments,"autoplay_time")||1E4},L3=function(a,b){var c=IGa(a,b),d=Math,e=d.min;
var f=(0,g.P)()-a.l;d=e.call(d,f,c);c=0===c?1:Math.min(d/c,1);a.C.setAttribute("stroke-dashoffset",""+-211*(c+1));1<=c&&a.Zg()&&!J3(a)?a.select(!0):a.Zg()&&a.i.start()},M3=function(a){I3.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=this.suggestions=null;this.table=new g.W({D:"div",K:"ytp-suggestion-panel",S:[{D:"div",ka:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],ba:"More videos"}]});this.J=new g.W({D:"div",K:"ytp-suggestions-container"});this.videos=[];this.u=null;this.C=this.I=!1;this.l=new F3(this.player);g.K(this,this.l);this.l.fa(this.element);a.getVideoData().xc?this.i=this.l:(this.i=new K3(a),g.ZN(this.player,this.i.element,4),g.K(this,this.i));this.overlay=
new g.W({D:"div",K:"ytp-autonav-overlay-cancelled-state"});g.K(this,this.overlay);this.overlay.fa(this.element);this.B=new g.aO(this);g.K(this,this.B);g.K(this,this.table);this.table.fa(this.element);this.table.show();g.K(this,this.J);this.J.fa(this.table.element);this.hide()},JGa=function(a,b){return g.Jc(b.suggestions,function(c){c=g.YQ(a.player.T(),c);
g.K(a,c);return c})},N3=function(a){var b=a.xd();
b!==a.C&&(a.C=b,a.player.V("autonavvisibility"),a.C?(a.l!==a.i&&a.l.hide(),a.table.hide()):(a.l!==a.i&&a.l.show(),a.table.show()))},O3=function(a){I3.call(this,a,"subscribecard-endscreen");
this.i=new g.W({D:"div",K:"ytp-subscribe-card",S:[{D:"img",K:"ytp-author-image",U:{src:"{{profilePicture}}"}},{D:"div",K:"ytp-subscribe-card-right",S:[{D:"div",K:"ytp-author-name",ba:"{{author}}"},{D:"div",K:"html5-subscribe-button-container"}]}]});g.K(this,this.i);this.i.fa(this.element);var b=a.getVideoData();this.subscribeButton=new g.jP("Subscribe",null,"Unsubscribe",null,!0,!1,b.Ig,b.subscribed,"trailer-endscreen",null,null,a);g.K(this,this.subscribeButton);this.subscribeButton.fa(this.i.ha("html5-subscribe-button-container"));
this.N(a,"videodatachange",this.wa);this.wa();this.hide()},P3=function(a){var b=a.T(),c=g.GA||g.xg?{style:"will-change: opacity"}:void 0,d=b.l,e=["ytp-videowall-still"];
b.i&&e.push("ytp-videowall-show-text");g.W.call(this,{D:"a",ka:e,U:{href:"{{url}}",target:d?b.C:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},S:[{D:"div",K:"ytp-videowall-still-image",U:{style:"{{background}}"}},{D:"span",K:"ytp-videowall-still-info",S:[{D:"span",K:"ytp-videowall-still-info-bg",S:[{D:"span",K:"ytp-videowall-still-info-content",U:c,S:[{D:"span",K:"ytp-videowall-still-info-title",ba:"{{title}}"},{D:"span",K:"ytp-videowall-still-info-author",
ba:"{{author_and_views}}"},{D:"span",K:"ytp-videowall-still-info-live",ba:"Live"},{D:"span",K:"ytp-videowall-still-info-duration",ba:"{{duration}}"}]}]}]},{D:"span",ka:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],S:[{D:"span",K:"ytp-videowall-still-listlabel-icon"},"Playlist",{D:"span",K:"ytp-videowall-still-listlabel-length",S:[" (",{D:"span",ba:"{{playlist_length}}"},")"]}]},{D:"span",ka:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],S:[{D:"span",
K:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{D:"span",K:"ytp-videowall-still-listlabel-length",ba:" (50+)"}]}]});this.suggestion=null;this.l=d;this.api=a;this.i=new g.aO(this);g.K(this,this.i);this.ya("click",this.onClick);this.ya("keypress",this.u);this.i.N(a,"videodatachange",this.Oa);a.Sg(this.element,this);this.Oa()},Q3=function(a){I3.call(this,a,"videowall-endscreen");
var b=this;this.G=a;this.u=0;this.stills=[];this.B=this.videoData=this.suggestions=null;this.C=this.J=!1;this.L=null;this.l=new g.aO(this);g.K(this,this.l);this.I=new g.L(function(){g.M(b.element,"ytp-show-tiles")},0);
g.K(this,this.I);var c=new g.W({D:"button",ka:["ytp-button","ytp-endscreen-previous"],U:{"aria-label":"Previous"},S:[g.YL()]});g.K(this,c);c.fa(this.element);c.ya("click",this.GJ,this);this.table=new g.QL({D:"div",K:"ytp-endscreen-content"});g.K(this,this.table);this.table.fa(this.element);c=new g.W({D:"button",ka:["ytp-button","ytp-endscreen-next"],U:{"aria-label":"Next"},S:[g.ZL()]});g.K(this,c);c.fa(this.element);c.ya("click",this.FJ,this);a.getVideoData().xc?this.i=new F3(a,!0):this.i=new K3(a);
g.K(this,this.i);g.ZN(this.player,this.i.element,4);this.hide()},R3=function(a){return g.$N(a.player)&&a.qq()&&!a.B},KGa=function(a,b){return g.Jc(b.suggestions,function(c){c=g.YQ(a.G.T(),c);
g.K(a,c);return c})},S3=function(a){var b=a.xd();
b!==a.J&&(a.J=b,a.player.V("autonavvisibility"))},T3=function(a){g.iO.call(this,a);
var b=this;this.endScreen=null;this.i=this.l=this.u=!1;this.listeners=new g.aO(this);g.K(this,this.listeners);this.env=a.T();LGa(a)?(this.u=!0,MGa(this),this.i?this.endScreen=new M3(a):this.endScreen=new Q3(this.player)):this.env.Dc?this.endScreen=new O3(this.player):this.endScreen=new I3(this.player);g.K(this,this.endScreen);g.ZN(this.player,this.endScreen.element,4);NGa(this);this.listeners.N(a,"videodatachange",this.Oa,this);this.listeners.N(a,g.sG("endscreen"),function(c){b.Ad(c)});
this.listeners.N(a,g.tG("endscreen"),function(c){b.nf(c)})},MGa=function(a){var b=a.player.getVideoData();
if(!b||a.i===b.bf&&a.l===b.xc)return!1;a.i=b.bf;a.l=b.xc;return!0},LGa=function(a){a=a.T();
return a.qb&&!a.Dc},NGa=function(a){a.player.Qe("endscreen");
var b=a.player.getVideoData();b=new g.pG(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.pG(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});a.player.Kd([b,c])};
g.SN.prototype.bn=g.ca(4,function(){return this.app.bn()});
g.sW.prototype.bn=g.ca(3,function(){return this.getVideoData().gH});
g.u(D3,g.W);D3.prototype.select=function(){(this.G.Ki(this.suggestion.Na().videoId,this.suggestion.Dd,this.suggestion.getPlaylistId(),void 0,void 0,this.suggestion.Kx||void 0)||this.G.Z("web_player_endscreen_double_log_fix_killswitch"))&&this.G.vb(this.element)};
D3.prototype.onClick=function(a){g.BO(a,this.G,this.i,this.suggestion.Dd||void 0)&&this.select()};
D3.prototype.l=function(a){switch(a.keyCode){case 13:case 32:g.hp(a)||(this.select(),g.gp(a))}};
D3.prototype.Xd=function(a){g.N(this.element,"ytp-suggestion-card-with-margin",a)};g.u(F3,g.W);g.k=F3.prototype;g.k.gq=function(a){this.suggestion!==a&&(this.suggestion=a,C3(this.i,a),this.playButton.Aa("url",this.suggestion.Bl()),this.Xd())};
g.k.Xd=function(){var a=this.G.ij(!0,this.G.isFullscreen());g.N(this.element,"ytp-autonav-endscreen-small-mode",this.Oe(a));g.N(this.element,"ytp-autonav-endscreen-is-premium",!!this.suggestion&&!!this.suggestion.lv);g.N(this.G.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!this.G.xd());g.N(this.G.getRootNode(),"countdown-running",this.Zg());g.N(this.element,"ytp-player-content",this.G.xd());g.ug(this.overlay.element,{width:a.width+"px"});if(!this.Zg()){this.G.xd()?H3(this,Math.round(G3(this)/
1E3)):H3(this);a=!!this.suggestion&&!!this.suggestion.rq;var b=this.G.xd()||!a;g.N(this.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!b&&a);g.N(this.element,"ytp-autonav-endscreen-upnext-no-alternative-header",b&&!a);g.TL(this.u,this.G.xd())}};
g.k.Zg=function(){return 0<this.l};
g.k.Hp=function(){this.Zg()||(this.l=Date.now(),E3(this),HGa(this.G,G3(this)),g.N(this.G.getRootNode(),"countdown-running",this.Zg()))};
g.k.En=function(){this.Fk();E3(this)};
g.k.Fk=function(){this.Zg()&&(this.B.stop(),this.l=0)};
g.k.select=function(a){this.G.nextVideo(!1,void 0===a?!1:a);this.Fk()};
g.k.GB=function(a){g.BO(a,this.G)&&(a.currentTarget===this.playButton.element?this.G.vb(this.playButton.element):a.currentTarget===this.i.ha("ytp-autonav-endscreen-link-container")&&(a=this.i.ha("ytp-autonav-endscreen-link-container"),this.G.Pa(a,!0),this.G.vb(a)),this.select())};
g.k.AJ=function(){this.G.vb(this.cancelButton.element);g.UN(this.G,!0)};
g.k.FB=function(){var a=this.G.xd();this.C&&this.ab!==a&&g.TL(this,a);this.Xd();this.G.Pa(this.element,a);this.G.Pa(this.cancelButton.element,a);this.G.Pa(this.i.ha("ytp-autonav-endscreen-link-container"),a);this.G.Pa(this.playButton.element,a)};
g.k.Oe=function(a){return 400>a.width||459>a.height};g.u(I3,g.W);g.k=I3.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.qq=function(){return!1};
g.k.xd=function(){return!1};
g.k.vE=function(){return!1};g.u(K3,g.W);g.k=K3.prototype;g.k.vt=function(){this.notification&&(this.B.stop(),this.Gb(this.u),this.u=null,this.notification.close(),this.notification=null)};
g.k.gq=function(a){this.suggestion=a;C3(this,a,"hqdefault.jpg")};
g.k.HB=function(){g.TL(this,this.api.xd());this.api.Pa(this.element,this.api.xd());this.api.Pa(this.ha("ytp-upnext-autoplay-icon"),this.api.xd());this.cancelButton&&this.api.Pa(this.cancelButton.element,this.api.xd())};
g.k.hO=function(){window.focus();this.vt()};
g.k.Hp=function(a){var b=this;this.Zg()||(g.Io("a11y-announce","Up Next "+this.suggestion.title),this.l=(0,g.P)(),this.i=new g.L(function(){L3(b,a)},25),L3(this,a),HGa(this.api,IGa(this,a)));
g.rn(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.W.prototype.hide.call(this)};
g.k.Zg=function(){return!!this.i};
g.k.En=function(){this.Fk();this.l=(0,g.P)();L3(this);g.M(this.element,"ytp-upnext-autoplay-paused")};
g.k.Fk=function(){this.Zg()&&(this.i.dispose(),this.i=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(g.S(this.api.T().experiments,"autonav_notifications")&&a&&window.Notification&&document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(b=this.suggestion.Na(),this.vt(),this.notification=new Notification("Up Next",{body:b.title,icon:b.ze()}),this.u=this.N(this.notification,"click",this.hO),this.B.start())}this.Fk();this.api.nextVideo(!1,a)};
g.k.CJ=function(a){!g.Je(this.cancelButton.element,g.cp(a))&&g.BO(a,this.api)&&(this.api.xd()&&this.api.vb(this.ha("ytp-upnext-autoplay-icon")),this.select())};
g.k.BJ=function(){this.api.xd()&&this.cancelButton&&this.api.vb(this.cancelButton.element);g.UN(this.api,!0)};
g.k.UN=function(a){J3(this);this.show();this.Hp(a)};
g.k.BH=function(a){J3(this);this.suggestion&&this.suggestion.Na().videoId===a.Na().videoId||this.gq(a)};
g.k.VN=function(){J3(this);this.Fk();this.hide()};
g.k.da=function(){this.Fk();this.vt();g.W.prototype.da.call(this)};g.u(M3,I3);g.k=M3.prototype;g.k.create=function(){I3.prototype.create.call(this);this.B.N(this.player,"appresize",this.Xd);this.B.N(this.player,"onVideoAreaChange",this.Xd);this.B.N(this.player,"videodatachange",this.Oa);this.B.N(this.player,"autonavchange",this.IB);this.B.N(this.player,"autonavcancel",this.DJ);this.Oa()};
g.k.show=function(){I3.prototype.show.call(this);(this.I||this.u&&this.u!==this.videoData.clientPlaybackNonce)&&g.UN(this.player,!1);g.$N(this.player)&&this.qq()&&!this.u?(N3(this),2===this.videoData.autonavState?this.player.T().Z("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.i.select(!0):this.i.Hp():3===this.videoData.autonavState&&this.i.En()):(g.UN(this.player,!0),N3(this));this.Xd()};
g.k.hide=function(){I3.prototype.hide.call(this);this.i.En();N3(this)};
g.k.Xd=function(){var a=this.player.ij(!0,this.player.isFullscreen());N3(this);this.l.Xd();g.N(this.element,"ytp-autonav-cancelled-small-mode",this.Oe(a));g.N(this.element,"ytp-autonav-cancelled-tiny-mode",this.ju(a));g.N(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.ug(this.overlay.element,{width:a.width+"px"});if(!this.C){a=g.q(this.videos.entries());for(var b=a.next();!b.done;b=a.next()){b=g.q(b.value);var c=b.next().value;b.next().value.Xd(1===c%2)}}};
g.k.Oa=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((this.suggestions=JGa(this,a))&&this.suggestions.length)for(this.i.gq(this.suggestions[0]),this.i!==this.l&&this.l.gq(this.suggestions[0]),a=0;a<OGa.length;++a){var b=OGa[a];if(this.suggestions&&this.suggestions[b]){this.videos[a]=new D3(this.player);var c=this.videos[a];b=this.suggestions[b];c.suggestion!==b&&(c.suggestion=b,C3(c,b));g.K(this,this.videos[a]);this.videos[a].fa(this.J.element)}}this.Xd()}};
g.k.IB=function(a){1===a?(this.I=!1,this.u=this.videoData.clientPlaybackNonce,this.i.Fk(),this.ab&&this.Xd()):(this.I=!0,this.xd()&&(2===a?this.i.Hp():3===a&&this.i.En()))};
g.k.DJ=function(a){a?this.IB(1):(this.u=null,this.I=!1)};
g.k.qq=function(){return 1!==this.videoData.autonavState};
g.k.Oe=function(a){return(910>a.width||459>a.height)&&!this.ju(a)&&!(400>=a.width||360>=a.height)};
g.k.ju=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.xd=function(){return this.ab&&g.$N(this.player)&&this.qq()&&!this.u};
var OGa=[1,3,2,4];g.u(O3,I3);O3.prototype.wa=function(){var a=this.player.getVideoData();this.i.update({profilePicture:a.hg,author:a.author});this.subscribeButton.channelId=a.Ig;var b=this.subscribeButton;a.subscribed?b.l():b.u()};g.u(P3,g.W);P3.prototype.select=function(){(this.api.Ki(this.suggestion.Na().videoId,this.suggestion.Dd,this.suggestion.getPlaylistId(),void 0,void 0,this.suggestion.Kx||void 0)||this.api.Z("web_player_endscreen_double_log_fix_killswitch"))&&this.api.vb(this.element)};
P3.prototype.onClick=function(a){g.BO(a,this.api,this.l,this.suggestion.Dd||void 0)&&this.select()};
P3.prototype.u=function(a){switch(a.keyCode){case 13:case 32:g.hp(a)||(this.select(),g.gp(a))}};
P3.prototype.Oa=function(){var a=this.api.getVideoData(),b=this.api.T();this.l=a.C?!1:b.l};g.u(Q3,I3);g.k=Q3.prototype;g.k.create=function(){I3.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.suggestions=KGa(this,a),this.videoData=a);this.Xd();this.l.N(this.player,"appresize",this.Xd);this.l.N(this.player,"onVideoAreaChange",this.Xd);this.l.N(this.player,"videodatachange",this.Oa);this.l.N(this.player,"autonavchange",this.ww);this.l.N(this.player,"autonavcancel",this.EJ);a=this.videoData.autonavState;a!==this.L&&this.ww(a);this.l.N(this.element,"transitionend",this.uP)};
g.k.destroy=function(){g.Rt(this.l);g.Yf(this.stills);this.stills=[];this.suggestions=null;I3.prototype.destroy.call(this);g.rn(this.element,"ytp-show-tiles");this.I.stop();this.L=this.videoData.autonavState};
g.k.qq=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){I3.prototype.show.call(this);g.rn(this.element,"ytp-show-tiles");this.player.T().i?this.I.Ug():this.I.start();(this.C||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.UN(this.player,!1);R3(this)?(S3(this),2===this.videoData.autonavState?this.player.T().Z("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.i.select(!0):this.i.Hp():3===this.videoData.autonavState&&this.i.En()):(g.UN(this.player,!0),S3(this))};
g.k.hide=function(){I3.prototype.hide.call(this);this.i.En();S3(this)};
g.k.uP=function(a){g.cp(a)===this.element&&this.Xd()};
g.k.Xd=function(){if(this.suggestions&&this.suggestions.length){g.M(this.element,"ytp-endscreen-paginate");var a=this.G.ij(!0,this.G.isFullscreen()),b=g.PN(this.G);b&&(b=b.Ae()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),h=Math.max(a.height/54,2),l=this.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<h);){var p=b/2,r=e/2,t=b<=f-2&&n>=r*m,w=e<=h-2&&n>=p*m;if((p+1)/r*d/c>c/(p/(r+1)*d)&&w)n-=p*m,e+=2;else if(t)n-=
r*m,b+=2;else if(w)n-=p*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m=Math.floor(Math.min(a.width,m*c));n=Math.floor(Math.min(a.height,n*c));a=this.table.element;g.Jg(a,m,n);g.ug(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});this.i.gq(this.suggestions[0]);this.i instanceof F3&&this.i.Xd();g.N(this.element,"ytp-endscreen-takeover",R3(this));S3(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(h=0;h<e;h++)if(p=c,r=0,d&&f>=b-2&&h>=e-2?
r=1:0===h%2&&0===f%2&&(2>h&&2>f?0===h&&0===f&&(r=2):r=2),p=g.$d(p+this.u,l),0!==r){t=this.stills[c];t||(t=new P3(this.player),this.stills[c]=t,a.appendChild(t.element));w=Math.floor(n*h/e);var x=Math.floor(m*f/b),y=Math.floor(n*(h+r)/e)-w-4,F=Math.floor(m*(f+r)/b)-x-4;g.Cg(t.element,x,w);g.Jg(t.element,F,y);g.ug(t.element,"transitionDelay",(h+f)/20+"s");g.N(t.element,"ytp-videowall-still-mini",1===r);g.N(t.element,"ytp-videowall-still-large",2<r);r=t;p=this.suggestions[p];r.suggestion!==p&&(r.suggestion=
p,t=r.api.T(),w=g.pn(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",C3(r,p,w),g.OC(t)&&(t=p.Bl(),t=g.Id(t,g.fP("emb_rel_end")),r.Aa("url",t)),(p=(p=p.Dd)&&p.itct)&&r.api.cm(r.element,p));c++}g.N(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.Ge(e.element),g.Xf(e);this.stills.length=c}};
g.k.Oa=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.u=0,this.suggestions=KGa(this,a),this.videoData=a,this.Xd())};
g.k.FJ=function(){this.u+=this.stills.length;this.Xd()};
g.k.GJ=function(){this.u-=this.stills.length;this.Xd()};
g.k.vE=function(){return this.i.Zg()};
g.k.ww=function(a){1===a?(this.C=!1,this.B=this.videoData.clientPlaybackNonce,this.i.Fk(),this.ab&&this.Xd()):(this.C=!0,this.ab&&R3(this)&&(2===a?this.i.Hp():3===a&&this.i.En()))};
g.k.EJ=function(a){if(a){for(a=0;a<this.stills.length;a++)this.G.Pa(this.stills[a].element,!0);this.ww(1)}else this.B=null,this.C=!1;this.Xd()};
g.k.xd=function(){return this.ab&&R3(this)};g.u(T3,g.iO);g.k=T3.prototype;g.k.Mn=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!LGa(this.player)||b;var c=a.Vc||g.YC(a.B),d=this.player.Qq();a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.k.xd=function(){return this.endScreen.xd()};
g.k.XL=function(){return this.xd()?this.endScreen.vE():!1};
g.k.da=function(){this.player.Qe("endscreen");g.iO.prototype.da.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.dE;if(b&&b.videoId){var c=this.player.Ua().dd.get("heartbeat");a&&a.suggestions&&a.suggestions.length&&b.videoId===a.suggestions[0].id&&!a.aC?a=!1:(this.player.Ki(b.videoId,void 0,void 0,!0,!0,b),c&&c.ru("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0)}else a=!1;a||(g.iO.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.iO.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.Ad=function(a){this.Mn()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.nf=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.Oa=function(){NGa(this);this.u&&MGa(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.i?this.endScreen=new M3(this.player):this.endScreen=new Q3(this.player),g.K(this,this.endScreen),g.ZN(this.player,this.endScreen.element,4))};g.oO.endscreen=T3;})(_yt_player);
